<#
.SYNOPSIS
    Category 1 (uncovered endpoints) and category 2 (parameter gaps) of the API drift
    report. Dot-sourced by tools/Build-PfbApiDriftReport.ps1 and its Pester tests.
    Category 3 (ValidateSet drift) lives here too -- see Get-PfbValidateSetDrift, added
    in a later task -- reusing Resolve-PfbFieldValueEnum from
    tools/lib/PfbValueEnumTools.ps1. Category 4 (new ValidateSet candidates) needs no new
    code at all: it's tools/Build-PfbFieldCmdletMap.ps1's existing 'matched' output,
    consumed directly by the orchestrator.
#>

# Deliberately NOT Set-StrictMode -- same reasoning as PfbSpecTools.ps1/PfbValueEnumTools.ps1.

# Endpoints reached exclusively through hand-written auth code that never calls
# Invoke-PfbApiRequest (it's what establishes the session Invoke-PfbApiRequest itself
# depends on) -- confirmed by reading Public/Connection/Connect-PfbArray.ps1,
# Public/Connection/Disconnect-PfbArray.ps1, and Private/Invoke-PfbOAuth2Login.ps1
# directly. admins/api-tokens is deliberately NOT here: Connect-PfbArray.ps1 also touches
# it via raw Invoke-RestMethod for post-login token minting, but GET/POST/DELETE
# admins/api-tokens are already covered through the standard Invoke-PfbApiRequest
# convention by Public/Admin/{Get,New,Remove}-PfbApiToken.ps1, so Get-PfbModuleCalledEndpoints's
# normal scan already sees them without needing this allowlist.
$script:PfbBespokeAuthEndpoints = @(
    'GET /api/api_version',
    'POST /api/login',
    'POST /api/logout',
    'POST /oauth2/1.0/token'
)

# Fields never worth reporting as a category-2 gap, each for its own confirmed reason --
# not the same list as $script:PfbBespokeAuthEndpoints (that's endpoint keys; this is
# field names). Deliberately excludes context_names/allow_errors/sort/total_only -- those
# change request *behavior* (fleet-context targeting, bulk-error tolerance, sorting,
# aggregate-only responses) and are real, if broad, gaps, not noise.
#   - X-Request-ID: no functional effect on the request -- request/response-log
#     correlation only ("Supplied by client during request or generated by server," per
#     the spec), present on 629/632 capability-map endpoints as of 2.27 with zero cmdlets
#     exposing it anywhere (confirmed via grep of Public/+Private/). No Private/ injection
#     site exists for it either -- confirmed by Get-PfbCentralInjectionSites finding zero
#     assignment sites for this key -- so it stays a hand-written entry: there is nothing
#     to derive an absence FROM.
#   - offset: an alternate, unused positioning mechanism into the same paginated
#     collections -AutoPaginate already retrieves in full; co-occurs with
#     continuation_token on 208/212 of its capability-map endpoints, and zero cmdlets
#     expose it. Same as X-Request-ID: no Private/ injection site exists, so this stays
#     hand-written too.
#
# continuation_token is DELIBERATELY NOT here any more (Task 6) -- it used to be, with a
# hand-written justification identical in spirit to the two above ("superseded by
# Invoke-PfbApiRequest's own -AutoPaginate"). That hand-written comment could go silently
# stale the moment Invoke-PfbApiRequest.ps1 changed shape -- e.g. if a future edit sourced
# it from a parameter instead of `$response`, or stopped injecting it at all -- with
# nothing to notice. It is now DERIVED instead, by Get-PfbNonActionableParameters (below),
# from Get-PfbCentralInjectionSites' live AST scan of Private/Invoke-PfbApiRequest.ps1's
# actual `$QueryParams['continuation_token'] = $response.continuation_token` assignment
# (currently line 227): its right-hand side traces to `$response` -- server-issued data
# from the just-completed Invoke-RestMethod call, never a cmdlet/caller parameter, so no
# caller could meaningfully supply this value even if a typed parameter existed for it.
# This is a STRONGER claim than the general injection-detection mechanism's usual
# "coverage, not correctness" caveat (see Get-PfbCentralInjectionSites/
# Get-PfbDerivedNonActionableParameters's own docs): continuation_token is structurally
# unable to ever become a cmdlet parameter, not merely "not currently seen as a gap".
$script:PfbNonActionableParameters = @(
    'X-Request-ID',
    'offset'
)

. (Join-Path $PSScriptRoot 'PfbValueEnumTools.ps1')
. (Join-Path $PSScriptRoot 'PfbCmdletParamTools.ps1')

function Test-PfbApiVersionNewerThan {
    <#
    .SYNOPSIS
        Tests whether REST version string -Version is numerically newer than -Baseline.
        Naive string comparison ranks '2.9' above '2.26' -- splits each into Major/Minor
        integers instead (same idiom as Get-PfbValueEnumHistory in PfbValueEnumTools.ps1).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]$Version,
        [Parameter(Mandatory)] [string]$Baseline
    )

    $vParts = $Version -split '\.'
    $bParts = $Baseline -split '\.'
    $vMajor = [int]$vParts[0]; $vMinor = [int]$vParts[1]
    $bMajor = [int]$bParts[0]; $bMinor = [int]$bParts[1]

    if ($vMajor -ne $bMajor) { return $vMajor -gt $bMajor }
    return $vMinor -gt $bMinor
}

function Get-PfbModuleCalledEndpoints {
    <#
    .SYNOPSIS
        Scans every Public/*.ps1 and Private/*.ps1 function for Invoke-PfbApiRequest
        calls, extracting each literal -Method/-Endpoint pair, normalized to the same
        "<METHOD> /<endpoint>" key format Data/PfbCapabilityMap.json uses (see
        Private/Assert-PfbApiCapability.ps1:40-41).
    .OUTPUTS
        [PSCustomObject]@{ Key; Method; Endpoint; Resolved; Cmdlet; File }[] -- Resolved
        is $false (Key/Method/Endpoint all $null) when a call's -Endpoint isn't a plain
        string literal (built dynamically via interpolation or a variable), never
        silently dropped or guessed at.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]$PublicDirectory,
        [Parameter(Mandatory)] [string]$PrivateDirectory
    )

    $results = [System.Collections.Generic.List[object]]::new()
    $files = @(Get-ChildItem -Path $PublicDirectory -Filter '*.ps1' -Recurse -File) +
             @(Get-ChildItem -Path $PrivateDirectory -Filter '*.ps1' -Recurse -File)

    foreach ($file in $files) {
        $tokens = $null; $parseErrors = $null
        $ast = [System.Management.Automation.Language.Parser]::ParseFile($file.FullName, [ref]$tokens, [ref]$parseErrors)
        $functionAsts = $ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)

        foreach ($funcAst in $functionAsts) {
            $commands = $funcAst.FindAll({
                param($n)
                $n -is [System.Management.Automation.Language.CommandAst] -and
                $n.GetCommandName() -eq 'Invoke-PfbApiRequest'
            }, $true)

            foreach ($cmd in $commands) {
                $method = $null; $endpoint = $null
                $elements = $cmd.CommandElements
                for ($i = 0; $i -lt $elements.Count; $i++) {
                    $el = $elements[$i]
                    if ($el -isnot [System.Management.Automation.Language.CommandParameterAst]) { continue }
                    $next = if ($i + 1 -lt $elements.Count) { $elements[$i + 1] } else { $null }
                    if (-not $next) { continue }
                    if ($el.ParameterName -eq 'Method' -and $next -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
                        $method = $next.Value
                    }
                    elseif ($el.ParameterName -eq 'Endpoint' -and $next -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
                        $endpoint = $next.Value
                    }
                }

                if ($method -and $endpoint) {
                    $normalizedEndpoint = '/' + $endpoint.TrimStart('/')
                    $results.Add([PSCustomObject]@{
                        Key      = "$($method.ToUpperInvariant()) $normalizedEndpoint"
                        Method   = $method.ToUpperInvariant()
                        Endpoint = $normalizedEndpoint
                        Resolved = $true
                        Cmdlet   = $funcAst.Name
                        File     = $file.FullName
                    })
                }
                else {
                    $results.Add([PSCustomObject]@{
                        Key      = $null
                        Method   = $null
                        Endpoint = $null
                        Resolved = $false
                        Cmdlet   = $funcAst.Name
                        File     = $file.FullName
                    })
                }
            }
        }
    }

    return $results
}

function Get-PfbEndpointCoverageGaps {
    <#
    .SYNOPSIS
        Category 1: every Data/PfbCapabilityMap.json endpoint key that no
        Get-PfbModuleCalledEndpoints result covers and that isn't on -BespokeAllowlist.
    .PARAMETER SinceVersion
        When given, only endpoints whose minVersion is strictly newer than this REST
        version are returned -- e.g. -SinceVersion '2.26' isolates gaps introduced by
        2.27 only, dropping the rest of the accumulated backlog.
    .OUTPUTS
        [PSCustomObject]@{ Endpoint; MinVersion }[]
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $CapabilityMap,
        [Parameter(Mandatory)] [object[]]$CalledEndpoints,
        [string[]]$BespokeAllowlist = @(),
        [string]$SinceVersion
    )

    $calledKeys = [System.Collections.Generic.HashSet[string]]::new([string[]]@(
        $CalledEndpoints | Where-Object { $_.Resolved } | ForEach-Object { $_.Key }
    ))

    foreach ($key in $CapabilityMap.endpoints.PSObject.Properties.Name) {
        if ($calledKeys.Contains($key)) { continue }
        if ($BespokeAllowlist -contains $key) { continue }
        $minVersion = $CapabilityMap.endpoints.$key.minVersion
        if ($SinceVersion -and -not (Test-PfbApiVersionNewerThan -Version $minVersion -Baseline $SinceVersion)) { continue }
        [PSCustomObject]@{
            Endpoint   = $key
            MinVersion = $minVersion
        }
    }
}

function Get-PfbParameterCoverageGaps {
    <#
    .SYNOPSIS
        Category 2: for each endpoint an existing cmdlet already calls, flags
        capability-map-known query parameters and request-body properties the cmdlet
        doesn't expose as a typed parameter. Gaps are ALWAYS computed -- there is no
        longer an all-or-nothing gate that discards an endpoint's real gaps just because
        ONE parameter on it has an unresolved surface (design decision 5: the old
        `$fullyMapped` gate's failure mode was silence -- ~70% of its non-Typed
        classifications turned out to be tool blindness, not real gaps, and none of it
        was visible because the report simply got quieter). Uncertainty from an
        unresolved (AttributesOnly/TypedUnresolved) parameter is instead carried
        per-endpoint as `Confidence` (see .OUTPUTS): such a parameter may already cover
        an apparent gap through a path this AST-only inventory can't see, so the gap
        lists can contain false positives on a 'partial'-confidence endpoint -- but they
        are never silently emptied because of that uncertainty.

        Output is split three ways instead of one flat list:
          - MissingQueryParameters: capability-map `parameters` the cmdlet doesn't expose.
          - MissingBodyProperties: capability-map `bodyProperties` the cmdlet doesn't
            expose AND that are NOT read-only in the newest ANALYSED spec (addable).
          - ReadOnlyFields: the same source, but read-only in the newest ANALYSED spec
            (not addable -- reported separately, never merged into MissingBodyProperties).
        Only 1 of 632 real endpoints has the same field name land in both the query and
        body lists (POST /workloads/placement-recommendations|placement_names) -- no
        dedup machinery is applied between them.
    .PARAMETER SinceVersion
        When given, a gap's missing-field lists are filtered down to only fields whose
        capability-map version is strictly newer than this REST version -- e.g.
        -SinceVersion '2.26' isolates fields introduced by 2.27 only. An endpoint whose
        every missing field predates -SinceVersion is dropped entirely (not emitted with
        empty lists).
    .PARAMETER ExcludedFields
        Field names never reported as a missing parameter, regardless of version --
        e.g. $script:PfbNonActionableParameters. Applied to BOTH
        MissingQueryParameters and MissingBodyProperties: every field in that allowlist
        happens to be query-side today, but nothing about the mechanism is query-only,
        so a future body-side addition is not silently ignored. An endpoint whose every
        missing field is excluded is dropped entirely (not emitted with empty lists).
    .PARAMETER CurrentSpecCapabilities
        Optional. Get-PfbSpecCapabilities's output for ONLY the single newest ANALYSED
        spec -- i.e. tools/specs/fb<value>.json where <value> is
        $CapabilityMap.generatedFrom[-1] -- never whatever happens to be newest on disk
        under tools/specs/, which can be ahead of the map (e.g. specs refreshed to 2.28
        without rebuilding a 2.27 map produces annotations that can't be reconciled with
        the gaps they sit next to). $CapabilityMap's own `parameters`/`bodyProperties`
        dictionaries accumulate every field ever seen across every ingested version and
        never record removal (Build-PfbCapabilityMap.ps1 is first-sight for both), so a
        field withdrawn from the API in a later spec still lingers there forever -- a
        "phantom". Without this parameter phantom fields are NOT filtered (a safe no-op
        default so unit tests built on synthetic capability maps, never cross-checked
        against a real spec, are unaffected); with it, a candidate missing field absent
        from the endpoint's CURRENT parameter/body-property set is dropped from every
        list rather than reported as an addable/read-only/query gap it does not actually
        exist to be. 13 real (endpoint, field) pairs hit this against fb2.27 today, all
        body-side (e.g. `PATCH /certificates|id` -- read-only 2.0-2.19, removed 2.20+).
    .OUTPUTS
        [PSCustomObject]@{ Endpoint; Cmdlets; MissingQueryParameters; MissingBodyProperties;
        ReadOnlyFields; Confidence }[], one entry per endpoint where at least one of the
        three field lists is non-empty. `notVerified` no longer exists anywhere in this
        shape -- not as a field, not as a bucket. Confidence is
        [PSCustomObject]@{ Level; UnresolvedParameters; EscapeHatchOnly; Caveat }:
          - Level is 'high' iff UnresolvedParameters is empty, else 'partial'.
          - UnresolvedParameters is [PSCustomObject]@{ Parameter; Surface; File; Line }[]
            -- every non-Typed (AttributesOnly or TypedUnresolved) parameter on any
            cmdlet calling this endpoint, Line coming from
            Get-PfbCmdletParameterInventory's Line field
            ($p.Extent.StartLineNumber) so every caveat is a click-through.
          - EscapeHatchOnly is the subset of UnresolvedParameters' Parameter names whose
            Surface is 'AttributesOnly' (a real -Attributes escape hatch exists --
            'TypedUnresolved' has none at all).
          - Caveat is a human-readable summary of what the confidence gap means for this
            endpoint's lists, or '' when Level is 'high'.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $CapabilityMap,
        [Parameter(Mandatory)] [object[]]$CmdletInventory,
        [Parameter(Mandatory)] [object[]]$CalledEndpoints,
        [string]$SinceVersion,
        [string[]]$ExcludedFields = @(),
        [object[]]$CurrentSpecCapabilities = @()
    )

    $inventoryByCmdlet = $CmdletInventory | Group-Object -Property Cmdlet -AsHashTable -AsString
    $endpointGroups = @($CalledEndpoints | Where-Object { $_.Resolved } | Group-Object -Property Key)

    # Endpoint key ("<METHOD> /<path>", matching Data/PfbCapabilityMap.json's own key
    # format) -> the Get-PfbSpecCapabilities record for that endpoint in the single
    # newest ANALYSED spec, used only for phantom-field exclusion (see
    # -CurrentSpecCapabilities above). A typed Dictionary, not a Hashtable: endpoint keys
    # are not API field names so this one specifically isn't exposed to the
    # .Keys-shadowing bug this function is otherwise built around avoiding, but nothing
    # in this task trusts that reasoning per-callsite.
    $currentByEndpoint = [System.Collections.Generic.Dictionary[string, object]]::new()
    foreach ($cap in $CurrentSpecCapabilities) {
        $currentByEndpoint["$($cap.Method) $($cap.Path)"] = $cap
    }

    $gaps = [System.Collections.Generic.List[object]]::new()

    foreach ($group in $endpointGroups) {
        $key = $group.Name
        $entry = $CapabilityMap.endpoints.$key
        if (-not $entry) { continue }

        $cmdlets = @($group.Group.Cmdlet | Select-Object -Unique)

        $exposedWireNames = [System.Collections.Generic.HashSet[string]]::new()
        $unresolved = [System.Collections.Generic.List[object]]::new()
        foreach ($cmdletName in $cmdlets) {
            # The Where-Object is load-bearing, not defensive noise: Group-Object
            # -AsHashTable yields $null for an absent key, and @($null) is a ONE-element
            # array whose single element is $null -- not the empty array it reads as.
            # Without it, this loop would run once with $row = $null and throw evaluating
            # $null.Surface. A cmdlet contributes zero inventory rows when every
            # parameter it declares is inventory-exempt (-Array/-Attributes are
            # plumbing, never inventoried -- see Get-PfbCmdletParameterInventory), which
            # is exactly the shape of the -Attributes-only write cmdlets (Update-PfbArray,
            # Update-PfbPasswordPolicy, Update-PfbSupport, ...). No rows means nothing to
            # report as unresolved for that cmdlet.
            $rows = @($inventoryByCmdlet[$cmdletName] | Where-Object { $null -ne $_ })
            foreach ($row in $rows) {
                if ($row.Surface -ne 'Typed') {
                    $unresolved.Add([PSCustomObject]@{
                        Parameter = $row.Parameter
                        Surface   = $row.Surface
                        File      = $row.File
                        Line      = $row.Line
                    })
                    continue
                }
                if ($row.WireName) { [void]$exposedWireNames.Add($row.WireName) }
            }
        }

        $currentCap = $null
        if ($currentByEndpoint.ContainsKey($key)) { $currentCap = $currentByEndpoint[$key] }
        $currentQueryNames = if ($currentCap) { [System.Collections.Generic.HashSet[string]]::new([string[]]@($currentCap.Parameters)) } else { $null }
        $currentBodyNames = if ($currentCap) { [System.Collections.Generic.HashSet[string]]::new([string[]]@($currentCap.BodyProperties)) } else { $null }

        # Typed Dictionary[string,string] for each of query/body, NOT a plain Hashtable --
        # this is the generalised fix for the keys-shadowing bug (a field literally named
        # "keys"/"count"/"values" hijacking .Keys/.Count/.Values member access on a
        # Hashtable/PSCustomObject-backed IDictionary). A real field named "keys" exists
        # today (DELETE /workloads/tags), and .get_Keys() below is real-member access on a
        # typed generic Dictionary, immune to that adapter trick (verified: a Hashtable
        # key literally named "keys" shadows .Keys and returns the key's VALUE instead of
        # the key collection; a Dictionary[string,string] with the same key does not).
        $queryFieldVersions = [System.Collections.Generic.Dictionary[string, string]]::new()
        if ($entry.parameters) { foreach ($p in $entry.parameters.PSObject.Properties) { $queryFieldVersions[$p.Name] = $p.Value } }
        $bodyFieldVersions = [System.Collections.Generic.Dictionary[string, string]]::new()
        if ($entry.bodyProperties) { foreach ($p in $entry.bodyProperties.PSObject.Properties) { $bodyFieldVersions[$p.Name] = $p.Value } }

        # @(...) wraps the WHOLE if/else, not just its true branch -- assigning an
        # if/else expression straight to a variable collapses an EMPTY array result
        # (the else branch, on every endpoint with no read-only body fields) to a bare
        # $null instead of an empty array (confirmed live: `$x = if ($false) {@(1)}
        # else {@()}` leaves $x -eq $null, not an empty array) -- the same family of
        # "assigning a statement's output straight to a variable silently unwraps it"
        # hazard already documented in tools/Build-PfbApiDriftReport.ps1 for a
        # single-element ForEach-Object result, just the zero-element counterpart here.
        $readOnlyList = @(if ($entry.readOnlyBodyProperties) { $entry.readOnlyBodyProperties } else { @() })
        $readOnlyNames = [System.Collections.Generic.HashSet[string]]::new([string[]]$readOnlyList)

        # Sort-Object on all three emitted lists below is load-bearing, not cosmetic: the
        # Dictionary[string,string]s above preserve insertion order, but that order comes
        # from $entry.parameters/$entry.bodyProperties, which were themselves deserialized
        # from JSON -- .NET's JSON property enumeration is documented as insertion order
        # for System.Text.Json but PSCustomObject's own PSObject.Properties enumeration is
        # NOT guaranteed to match it, and (independent of that) two Hashtable-staged
        # candidate sets built earlier in this file's history silently reordered
        # run-to-run on identical input purely from .NET's per-process-randomized string
        # hash codes (confirmed live: regenerating the drift report twice produced two
        # byte-different files for the same underlying content). Sorting explicitly here
        # is what makes MissingQueryParameters/MissingBodyProperties/ReadOnlyFields
        # deterministic regardless of any of that.
        $missingQuery = @($queryFieldVersions.get_Keys() |
                Where-Object { -not $exposedWireNames.Contains($_) } |
                Where-Object { -not $currentQueryNames -or $currentQueryNames.Contains($_) })
        if ($SinceVersion) {
            $missingQuery = @($missingQuery | Where-Object { Test-PfbApiVersionNewerThan -Version $queryFieldVersions[$_] -Baseline $SinceVersion })
        }
        if ($ExcludedFields) {
            $missingQuery = @($missingQuery | Where-Object { $ExcludedFields -notcontains $_ })
        }
        $missingQuery = @($missingQuery | Sort-Object)

        $missingBodyCandidates = @($bodyFieldVersions.get_Keys() |
                Where-Object { -not $exposedWireNames.Contains($_) } |
                Where-Object { -not $currentBodyNames -or $currentBodyNames.Contains($_) })
        if ($SinceVersion) {
            $missingBodyCandidates = @($missingBodyCandidates | Where-Object { Test-PfbApiVersionNewerThan -Version $bodyFieldVersions[$_] -Baseline $SinceVersion })
        }
        if ($ExcludedFields) {
            $missingBodyCandidates = @($missingBodyCandidates | Where-Object { $ExcludedFields -notcontains $_ })
        }

        $readOnlyFields = @($missingBodyCandidates | Where-Object { $readOnlyNames.Contains($_) } | Sort-Object)
        $missingBody = @($missingBodyCandidates | Where-Object { -not $readOnlyNames.Contains($_) } | Sort-Object)

        if ($missingQuery.Count -eq 0 -and $missingBody.Count -eq 0 -and $readOnlyFields.Count -eq 0) { continue }

        $escapeHatchOnly = @($unresolved | Where-Object { $_.Surface -eq 'AttributesOnly' } | ForEach-Object { $_.Parameter } | Sort-Object -Unique)
        $hasBareUnresolved = [bool]($unresolved | Where-Object { $_.Surface -eq 'TypedUnresolved' })
        $level = if ($unresolved.Count -eq 0) { 'high' } else { 'partial' }
        $caveat =
        if ($level -eq 'high') { '' }
        elseif ($escapeHatchOnly.Count -gt 0 -and -not $hasBareUnresolved) {
            'body reachable only via -Attributes; lists reflect typed-parameter coverage, not wire reachability'
        }
        elseif ($escapeHatchOnly.Count -eq 0 -and $hasBareUnresolved) {
            'one or more parameters could not be traced to a wire name and have no -Attributes escape hatch; lists reflect typed-parameter coverage only, not full wire reachability'
        }
        else {
            'body reachable via -Attributes for some parameters and untraceable for others; lists reflect typed-parameter coverage only, not full wire reachability'
        }

        $confidence = [PSCustomObject]@{
            Level                = $level
            UnresolvedParameters = @($unresolved | Sort-Object Parameter, File, Line)
            EscapeHatchOnly      = $escapeHatchOnly
            Caveat               = $caveat
        }

        $gaps.Add([PSCustomObject]@{
                Endpoint              = $key
                Cmdlets               = $cmdlets
                MissingQueryParameters = $missingQuery
                MissingBodyProperties  = $missingBody
                ReadOnlyFields         = $readOnlyFields
                Confidence             = $confidence
            })
    }

    return $gaps.ToArray()
}

function Get-PfbValidateSetDrift {
    <#
    .SYNOPSIS
        Category 3: flags a typed Public/ parameter whose hand-written ValidateSet
        disagrees with the spec's current documented value list for the same field --
        missing values (the spec documents a legal value the ValidateSet rejects
        client-side, e.g. the real Get-PfbArrayPerformance -Protocol 'all' bug),
        stale values (the ValidateSet allows a value the spec no longer, or never did,
        document), or both.
    .OUTPUTS
        [PSCustomObject]@{ Cmdlet; Parameter; CurrentValidateSet; SpecValues;
        MissingValues; StaleValues }[] -- only for parameters whose wire name resolves
        to exactly one spec value-enum record ('matched' via Resolve-PfbFieldValueEnum);
        a HasValidateSet parameter that resolves to 'collision'/'not-found-in-resource'/
        'no-spec-enum-found' is silently excluded (not enough signal to compare against).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [object[]]$CmdletInventory,
        [Parameter(Mandatory)] $History,
        [Parameter(Mandatory)] [string]$OldestVersion
    )

    $withValidateSet = @($CmdletInventory | Where-Object { $_.Surface -eq 'Typed' -and $_.HasValidateSet })

    foreach ($cand in $withValidateSet) {
        $hint = Get-PfbResourceHint -CmdletName $cand.Cmdlet
        $resolution = Resolve-PfbFieldValueEnum -WireName $cand.WireName -ResourceHint $hint -Endpoint $cand.Endpoint -Method $cand.Method -History $History -OldestVersion $OldestVersion
        if ($resolution.Status -ne 'matched') { continue }

        $current = @($cand.ValidateSetValues)
        $spec = @($resolution.SpecValues)
        $missing = @($spec | Where-Object { $current -notcontains $_ })
        $stale = @($current | Where-Object { $spec -notcontains $_ })

        if ($missing.Count -eq 0 -and $stale.Count -eq 0) { continue }

        [PSCustomObject]@{
            Cmdlet             = $cand.Cmdlet
            Parameter          = $cand.Parameter
            CurrentValidateSet = $current
            SpecValues         = $spec
            MissingValues      = $missing
            StaleValues        = $stale
        }
    }
}

# --- Task 5: per-field enrichment + enum join for MissingBodyProperties -----------------
#
# Consumed by tools/Build-PfbApiDriftReport.ps1, which ONLY calls this enrichment path for
# an endpoint whose Confidence.Level is 'high' -- a 'partial'-confidence endpoint's
# MissingBodyProperties list can contain false positives (see Get-PfbParameterCoverageGaps's
# own .OUTPUTS help: an unresolved parameter may already cover an apparent gap through a
# path this AST-only inventory cannot see), and handing a human a fully-worked-out
# suggestedPowerShellType/target/enumValues for a field that might not even be a real gap
# would overstate the confidence the endpoint's own `confidence.caveat` is explicitly
# telling them NOT to have. This is NOT a suppression (design decision 5 still holds --
# every field name still appears, unchanged, in a partial-confidence endpoint's list): it
# only withholds this task's EXTRA metadata layer, never the gap itself.
#
# This gating is not a guess -- it is what makes this task's own pinned acceptance numbers
# reproducible. Measured against the real capability map + specs (2026-07-26): 402 addable
# MissingBodyProperties entries on 'high'-confidence endpoints vs. 605 across BOTH
# confidence levels. The enum-join split this task's acceptance is pinned to -- 33 matched /
# 43 not-found-in-resource / 326 no-spec-enum-found -- reproduces EXACTLY over the
# high-confidence-only 402, and does NOT reproduce over the combined 605 (which instead
# gives 43 matched / 66 not-found-in-resource / 496 no-spec-enum-found) -- confirming the
# gate is the intended scope, not an afterthought.

# Sentinel -ResourceHint passed to Resolve-PfbFieldValueEnum when a body property's
# OwnerSchema is $null (no named component encloses its declaration -- see
# Get-PfbSchemaPropertyDetails's OwnerSchema doc in tools/lib/PfbSpecTools.ps1).
# Resolve-PfbFieldValueEnum matches -ResourceHint with "-like `"$ResourceHint*`"" against
# schema-kind history keys, so passing '' would degrade to a bare '*' wildcard that matches
# EVERY schema-kind entry in the whole history -- exactly wrong for "there is no owner to
# hint at". This sentinel starts with a character ('(') no real OpenAPI schema name in this
# spec uses, so it is guaranteed to prefix-match zero real history keys, correctly forcing
# the hinted-schema candidate set to stay empty rather than accidentally matching
# everything. Only 1 of the 402 real high-confidence addable body-property gaps hits this
# (POST /keytabs/upload|keytab_file -- a fully inline request body with no named schema
# anywhere in its chain) -- confirmed by real-data verification.
$script:PfbNoOwnerSchemaResourceHint = '(no-owner-schema)'

function Get-PfbSuggestedPowerShellType {
    <#
    .SYNOPSIS
        Maps an OpenAPI {type, format} pair (plus, for an array, its element {type, format})
        to a suggested PowerShell parameter type literal, e.g. '[string]', '[long]',
        '[string[]]'.
    .DESCRIPTION
        Table (verbatim from the drift-report-actionable-plan brief):
          integer + format 'int64'             -> [long]
          integer + format 'int32'/'uint32'/''  -> [int]   (also the fallback for any OTHER
                                                             unrecognised integer format,
                                                             since [int]/Int32 is the
                                                             OpenAPI/JSON-Schema default
                                                             width for "integer" when format
                                                             is absent)
          number  (any format, incl. 'double'/'float'/none) -> [double]
          string  (any format)                  -> [string]
          boolean                                -> [bool]
          array                                  -> "[<element>[]]", element mapped by a
                                                     RECURSIVE call against -ItemType/
                                                     -ItemFormat (falls back to [object] if
                                                     the item type could not be resolved --
                                                     e.g. OwnerSchema was $null, or the
                                                     array's own "items" node is itself an
                                                     unresolved $ref with no inline "type",
                                                     which this function deliberately does
                                                     NOT follow -- see
                                                     Get-PfbBodyPropertyArrayItemType)
          anything else ($null, '', 'object', or an unrecognised type string) -> [object],
              a deliberately honest fallback, never a guessed scalar type. This function's
              caller always ALSO emits the raw type/format alongside this suggestion (see
              Build-PfbApiDriftReport.ps1), so a human overriding a wrong/absent guess has
              the real spec facts to work from, not just this function's guess.

        Branches on FORMAT, not just TYPE, for integers specifically because silently is
        the dangerous failure mode here: 37 of the 402 real high-confidence addable
        body-property fields are `type: integer, format: int64` (measured against the real
        capability map + fb2.27 spec, 2026-07-26 -- NOT the 230 the original brief
        speculated; that figure was investigated and could not be reproduced against any of
        six candidate populations, see tools/README.md). Mapping bare `"type": "integer"`
        to `[int]` (Int32) without checking `format` would silently truncate every one of
        those 37 real fields the first time a caller supplied a value above 2^31-1.
    .OUTPUTS
        String, e.g. '[string]', '[long]', '[string[]]'. Never $null or ''.
    #>
    [CmdletBinding()]
    param(
        [AllowNull()] [string]$Type,
        [AllowNull()] [string]$Format,
        [AllowNull()] [string]$ItemType,
        [AllowNull()] [string]$ItemFormat
    )

    switch ($Type) {
        'integer' {
            if ($Format -eq 'int64') { return '[long]' }
            return '[int]'
        }
        'number' { return '[double]' }
        'string' { return '[string]' }
        'boolean' { return '[bool]' }
        'array' {
            $inner = Get-PfbSuggestedPowerShellType -Type $ItemType -Format $ItemFormat
            # Strip exactly the OUTERMOST leading '[' / trailing ']' via anchored regex
            # (never Trim(), which strips every matching char from each end and would
            # over-strip a nested array-of-array's inner brackets too, e.g. Trim('[',']')
            # on '[string[]]' yields 'string', not the intended 'string[]').
            $innerBare = $inner -replace '^\[', '' -replace '\]$', ''
            return "[$innerBare[]]"
        }
        default { return '[object]' }
    }
}

function Find-PfbOwnSchemaPropertyNode {
    <#
    .SYNOPSIS
        Internal helper for Get-PfbBodyPropertyArrayItemType/Get-PfbBodyPropertySynopsis:
        finds -FieldName's own (raw, un-resolved-further) property node within ONE already-
        identified named schema (-SchemaNode), searching its OWN inline "allOf" branches
        but never crossing into a "$ref" branch.
    .DESCRIPTION
        Real-data correction (measured against fb2.27, 2026-07-26): the majority of real
        OwnerSchema values -- e.g. `_certificateBase`, `NfsExportPolicyRuleBase`,
        `ActiveDirectoryPatch`, `SmbSharePolicyRule` -- carry NO "properties" key directly
        at their own top level; the schema is `{ allOf: [ {$ref: ...}, {properties: {...}} ] }`
        and the field lives in the anonymous SECOND branch's own "properties". This is
        exactly the shape Get-PfbSchemaPropertyDetails's OwnerSchema attribution already
        anticipates ("OwnerSchema is the nearest enclosing NAMED component whose properties
        block directly declares this property" -- an ANONYMOUS inline allOf branch is never
        itself an owner, so its declared properties are attributed to the nearest NAMED
        ancestor, i.e. THIS schema, even though they physically live one level down inside
        its own allOf). A single-hop `schema.properties.$FieldName` lookup (the original,
        too-naive implementation) therefore returned $null for nearly every real match,
        silently defeating both `synopsis` and the array-item-type lookup.

        This is still NOT "a second schema walker" in the decision-3 sense: it only
        descends into -SchemaNode's OWN anonymous ("allOf" with no "$ref") branches --
        never crosses into a "$ref" branch (that branch's properties belong to a DIFFERENT
        named schema, whatever OwnerSchema attribution assigned it there -- searching into
        it here would either find the wrong owner's field, or, worse, silently succeed for
        the wrong reason if two schemas happen to share a field name) -- and never resolves
        a property's OWN "$ref" or descends into ITS body (same top-level-only boundary
        Get-PfbSchemaPropertyDetails's PIN already establishes). The recursion is bounded
        and terminates naturally: it can only ever re-enter THIS one schema's own inline
        branches, never a different named schema.
    .OUTPUTS
        The raw property node (PSCustomObject), or $null.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [AllowNull()]
        $SchemaNode,

        [Parameter(Mandatory)]
        [string]$FieldName
    )

    if ($null -eq $SchemaNode) { return $null }

    if ($SchemaNode.PSObject.Properties.Name -contains 'properties' -and $SchemaNode.properties -and
        $SchemaNode.properties.PSObject.Properties.Name -contains $FieldName) {
        return $SchemaNode.properties.$FieldName
    }

    if ($SchemaNode.PSObject.Properties.Name -contains 'allOf' -and $SchemaNode.allOf) {
        foreach ($branch in $SchemaNode.allOf) {
            if ($branch.PSObject.Properties.Name -contains '$ref') { continue }
            $found = Find-PfbOwnSchemaPropertyNode -SchemaNode $branch -FieldName $FieldName
            if ($null -ne $found) { return $found }
        }
    }

    return $null
}

function Get-PfbOwnerSchemaPropertyNode {
    <#
    .SYNOPSIS
        Resolves -FieldName's own raw property node under -OwnerSchema in -Spec, or $null.
        Shared by Get-PfbBodyPropertyArrayItemType and Get-PfbBodyPropertySynopsis so both
        apply the exact same "which named schema, which branch" resolution -- see
        Find-PfbOwnSchemaPropertyNode for why a single top-level dictionary hop is not
        enough on real data.
    .OUTPUTS
        The raw property node (PSCustomObject), or $null.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $Spec,
        [AllowNull()] [string]$OwnerSchema,
        [Parameter(Mandatory)] [string]$FieldName
    )

    if (-not $OwnerSchema) { return $null }
    if (-not $Spec.components -or -not $Spec.components.schemas) { return $null }
    if ($Spec.components.schemas.PSObject.Properties.Name -notcontains $OwnerSchema) { return $null }

    $schema = $Spec.components.schemas.$OwnerSchema
    return Find-PfbOwnSchemaPropertyNode -SchemaNode $schema -FieldName $FieldName
}

function Get-PfbBodyPropertyArrayItemType {
    <#
    .SYNOPSIS
        For an array-typed body property, returns its element {Type, Format} via a DIRECT
        lookup of the property's own node under -OwnerSchema (see
        Get-PfbOwnerSchemaPropertyNode/Find-PfbOwnSchemaPropertyNode) -- never a second
        schema walker in the decision-3 sense (it never crosses into a DIFFERENT named
        schema or resolves any "$ref"). Reads exactly one property hop beyond that node:
        its own "items" sibling key (see Get-PfbSchemaPropertyDetails's PIN: it never
        follows a property's own "$ref" or descends further, and this respects the same
        boundary for "items").
    .DESCRIPTION
        $null when -OwnerSchema is $null (no named component encloses the property's
        declaration -- this function does not attempt to re-derive one by walking the
        operation's own inline body schema), when the named schema (searched through its
        own inline allOf branches, never a $ref'd one) doesn't declare -FieldName at all,
        or when the property has no "items" node (not actually an array, or "items" is
        itself an unresolved $ref with no inline "type"/"format" sibling -- deliberately
        not resolved, same "top-level only" rule Get-PfbSchemaPropertyDetails already
        applies one level up).
    .OUTPUTS
        [PSCustomObject]@{ Type; Format }, or $null.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $Spec,
        [AllowNull()] [string]$OwnerSchema,
        [Parameter(Mandatory)] [string]$FieldName
    )

    $propNode = Get-PfbOwnerSchemaPropertyNode -Spec $Spec -OwnerSchema $OwnerSchema -FieldName $FieldName
    if ($null -eq $propNode) { return $null }
    if ($propNode.PSObject.Properties.Name -notcontains 'items' -or -not $propNode.items) { return $null }

    $itemsNode = $propNode.items
    $itemType = if ($itemsNode.PSObject.Properties.Name -contains 'type') { $itemsNode.type } else { $null }
    $itemFormat = if ($itemsNode.PSObject.Properties.Name -contains 'format') { $itemsNode.format } else { $null }

    # An "items" node that is itself an unresolved $ref (e.g. { "$ref": "#/components/schemas/_tagRef" })
    # carries neither -- deliberately NOT followed (would be resolving one level further
    # than this function's own direct-lookup contract allows). Return $null overall in
    # that case, same as "no items node at all", rather than a half-populated record with
    # both fields $null -- the caller (Get-PfbBodyPropertyEnrichment) only ever checks
    # truthiness of this function's result before reading .Type/.Format.
    if (-not $itemType -and -not $itemFormat) { return $null }

    return [PSCustomObject]@{ Type = $itemType; Format = $itemFormat }
}

function Get-PfbBodyPropertySynopsis {
    <#
    .SYNOPSIS
        First sentence of a body property's own `description`, newline-normalised -- a
        DIRECT lookup of the property's own node under -OwnerSchema (see
        Get-PfbOwnerSchemaPropertyNode), never a second schema walker in the decision-3
        sense (never crosses into a different named schema or resolves a "$ref").
        Get-PfbSchemaPropertyDetails (tools/lib/PfbSpecTools.ps1) already did the hard part
        -- resolving the property's OWNING named schema through the allOf/$ref chain across
        MULTIPLE schemas; finding that one field's own node inside the schema already
        identified as its owner is a bounded, much smaller problem, so it does not earn a
        second walker.
    .DESCRIPTION
        $null when -OwnerSchema is $null (no named component encloses the property's
        declaration -- the operation's entire body schema was written fully inline with no
        $ref anywhere in its chain). This function does NOT attempt to re-derive an owner by
        re-walking the operation's own inline body schema (that would be a second walker).
        Also $null when the named schema (searched through its own inline allOf branches,
        never a $ref'd one -- see Find-PfbOwnSchemaPropertyNode) doesn't declare -FieldName
        at all, or declares it with no (or empty) "description" -- surfaced as $null rather
        than a wrong guess in every case, never a silently-empty string standing in for "no
        synopsis available".
        "First sentence": newlines are first replaced with a single space (these
        descriptions wrap mid-sentence in the raw spec text), then the result up to and
        including the first '.', '!', or '?' that is followed by whitespace or the end of
        the string is taken. Sampled real fb2.27 descriptions do not use a
        sentence-ending-like abbreviation before the field's own first true sentence break,
        so this simple split is not a compromise for that data -- but it IS naive prose
        parsing, not a guarantee for arbitrary future spec text.
    .OUTPUTS
        String, or $null.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $Spec,
        [AllowNull()] [string]$OwnerSchema,
        [Parameter(Mandatory)] [string]$FieldName
    )

    $propNode = Get-PfbOwnerSchemaPropertyNode -Spec $Spec -OwnerSchema $OwnerSchema -FieldName $FieldName
    if ($null -eq $propNode) { return $null }
    if ($propNode.PSObject.Properties.Name -notcontains 'description' -or -not $propNode.description) { return $null }

    $normalised = ($propNode.description -replace '\r?\n', ' ').Trim()
    $m = [regex]::Match($normalised, '^.*?[.!?](?=\s|$)')
    if ($m.Success) { return $m.Value.Trim() }
    return $normalised
}

function Get-PfbBodyPropertyEnrichment {
    <#
    .SYNOPSIS
        Composes every per-field enrichment fact Task 5 adds for ONE addable
        missing-body-property gap: synopsis, suggested PowerShell type, and the
        Resolve-PfbFieldValueEnum join.
    .DESCRIPTION
        The enum join always goes through Resolve-PfbFieldValueEnum, NEVER a bare wire-name
        lookup -- bare-name lookup is exactly the collision class (43 of the 402 real
        high-confidence addable gaps) this function exists to resolve correctly instead of
        guessing. -OwnerSchema (from Get-PfbSchemaPropertyDetails, via the caller's own
        BodyPropertyDetails lookup) is passed as -ResourceHint -- NOT the older
        cmdlet-name-derived Get-PfbResourceHint, which only reaches 14 of the 33 real
        matches (verified: Update-PfbNfsExportRule's derived hint 'NfsExportRule' does not
        prefix-match the real owning schema 'NfsExportPolicyRuleBase' at all). When
        -OwnerSchema is $null, $script:PfbNoOwnerSchemaResourceHint is substituted so the
        hint can never accidentally wildcard-match every schema-kind entry (see that
        variable's own comment).
    .OUTPUTS
        [PSCustomObject]@{ Synopsis; SuggestedPowerShellType; EnumValues; EnumStatus }.
        EnumStatus is always one of Resolve-PfbFieldValueEnum's own literal values --
        'matched' / 'collision' / 'not-found-in-resource' / 'no-spec-enum-found' -- passed
        through VERBATIM, never renamed or coerced. (Note for anyone cross-referencing the
        drift-report-actionable-plan's decisions register: its prose invents a 'collision'
        bucket meaning "collision-class", but the real function returns
        'not-found-in-resource' for that entire population in real data -- 0 real
        'collision' results occur among the 402 high-confidence addable gaps. This function
        still passes 'collision' through unchanged on the rare/future occasion
        Resolve-PfbFieldValueEnum actually returns it, rather than hardcoding it away.)
        EnumValues is always an array, empty (never $null) unless EnumStatus is 'matched'.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]$FieldName,
        [AllowNull()] [string]$Type,
        [AllowNull()] [string]$Format,
        [AllowNull()] [string]$OwnerSchema,
        [Parameter(Mandatory)] $Spec,
        [string]$Endpoint,
        [string]$Method,
        [Parameter(Mandatory)] $History,
        [Parameter(Mandatory)] [string]$OldestVersion
    )

    $synopsis = Get-PfbBodyPropertySynopsis -Spec $Spec -OwnerSchema $OwnerSchema -FieldName $FieldName

    $itemType = $null
    $itemFormat = $null
    if ($Type -eq 'array') {
        $items = Get-PfbBodyPropertyArrayItemType -Spec $Spec -OwnerSchema $OwnerSchema -FieldName $FieldName
        if ($items) { $itemType = $items.Type; $itemFormat = $items.Format }
    }
    $suggestedType = Get-PfbSuggestedPowerShellType -Type $Type -Format $Format -ItemType $itemType -ItemFormat $itemFormat

    $hint = if ($OwnerSchema) { $OwnerSchema } else { $script:PfbNoOwnerSchemaResourceHint }
    $resolution = Resolve-PfbFieldValueEnum -WireName $FieldName -ResourceHint $hint -Endpoint $Endpoint -Method $Method -History $History -OldestVersion $OldestVersion
    $enumValues = @(if ($resolution.Status -eq 'matched') { $resolution.SpecValues } else { @() })

    return [PSCustomObject]@{
        Synopsis                = $synopsis
        SuggestedPowerShellType = $suggestedType
        EnumValues              = $enumValues
        EnumStatus              = $resolution.Status
    }
}

# --- Task 6: systemic-gaps aggregation, convention strength, annotations, injection detection --

function Get-PfbGapFieldName {
    <#
    .SYNOPSIS
        Internal helper: the wire name a MissingQueryParameters/MissingBodyProperties list
        ENTRY represents, whether that entry is a bare string (Get-PfbParameterCoverageGaps'
        own, always-bare-string shape) or an enriched record
        (Build-PfbApiDriftReport.ps1's `{ name, type, format, ... }` shape, applied ONLY to
        high-confidence MissingBodyProperties -- see Get-PfbBodyPropertyEnrichment). Kept
        tolerant of both shapes so Get-PfbSystemicGaps works whether it's handed
        Get-PfbParameterCoverageGaps' raw output (this task's own real-data verification) or
        a later, already-enriched report structure (Task 7's job, not this task's).
    .OUTPUTS
        string, or $null if -Entry is neither shape.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [AllowNull()]
        $Entry
    )

    if ($null -eq $Entry) { return $null }
    if ($Entry -is [string]) { return $Entry }
    if ($Entry.PSObject.Properties.Name -contains 'name') { return $Entry.name }
    return $null
}

function Get-PfbSystemicGaps {
    <#
    .SYNOPSIS
        Decision 7: collapses Get-PfbParameterCoverageGaps's per-endpoint
        MissingQueryParameters/MissingBodyProperties lists into ONE finding PER DISTINCT
        WIRE NAME, across every endpoint AND both lists together -- e.g. `context_names`
        showing up as a missing query parameter on 252 different endpoints becomes a
        SINGLE finding with an EndpointCount of 252, not 252 separate per-endpoint rows.
        This is what turns hundreds of individual gap rows into a handful of real,
        actionable decisions.
    .DESCRIPTION
        An endpoint whose SAME field name happens to appear in both its own
        MissingQueryParameters and MissingBodyProperties (measured against the real
        capability map: exactly 1 real case, POST /workloads/placement-recommendations|
        placement_names -- see Get-PfbParameterCoverageGaps's own .OUTPUTS help) still
        contributes that endpoint only ONCE to the name's EndpointCount: endpoints are
        deduplicated per name via a HashSet, never concatenated across the two lists.
        Entries are read through Get-PfbGapFieldName so this tolerates either
        Get-PfbParameterCoverageGaps's own bare-string lists or an already-enriched
        MissingBodyProperties record shape.
    .OUTPUTS
        [PSCustomObject]@{ Name; EndpointCount; Endpoints; QueryEndpointCount;
        BodyEndpointCount }[], sorted by EndpointCount descending, then Name ascending.
        Endpoints is the sorted, deduplicated list of "<METHOD> /<path>" endpoint keys.
        QueryEndpointCount/BodyEndpointCount are the (possibly-overlapping) counts of
        endpoints where the name showed up specifically in MissingQueryParameters /
        MissingBodyProperties -- informational only; EndpointCount is always the
        deduplicated total, never their sum.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [AllowEmptyCollection()]
        [object[]]$Gaps
    )

    # Typed Dictionary[string, T], not a plain Hashtable, for every one of these three maps
    # -- a wire field literally named 'keys'/'count'/'values' would shadow .Keys/.Count/
    # .Values member access on a Hashtable-backed IDictionary (the same hazard
    # Get-PfbParameterCoverageGaps's own $queryFieldVersions/$bodyFieldVersions already
    # avoid, see its comment above them).
    $endpointsByName = [System.Collections.Generic.Dictionary[string, object]]::new()
    $queryCountByName = [System.Collections.Generic.Dictionary[string, int]]::new()
    $bodyCountByName = [System.Collections.Generic.Dictionary[string, int]]::new()

    foreach ($gap in $Gaps) {
        foreach ($rawEntry in @($gap.MissingQueryParameters)) {
            $name = Get-PfbGapFieldName -Entry $rawEntry
            if (-not $name) { continue }
            if (-not $endpointsByName.ContainsKey($name)) { $endpointsByName[$name] = [System.Collections.Generic.HashSet[string]]::new() }
            [void]$endpointsByName[$name].Add($gap.Endpoint)
            if (-not $queryCountByName.ContainsKey($name)) { $queryCountByName[$name] = 0 }
            $queryCountByName[$name] = $queryCountByName[$name] + 1
        }
        foreach ($rawEntry in @($gap.MissingBodyProperties)) {
            $name = Get-PfbGapFieldName -Entry $rawEntry
            if (-not $name) { continue }
            if (-not $endpointsByName.ContainsKey($name)) { $endpointsByName[$name] = [System.Collections.Generic.HashSet[string]]::new() }
            [void]$endpointsByName[$name].Add($gap.Endpoint)
            if (-not $bodyCountByName.ContainsKey($name)) { $bodyCountByName[$name] = 0 }
            $bodyCountByName[$name] = $bodyCountByName[$name] + 1
        }
    }

    $findings = [System.Collections.Generic.List[object]]::new()
    foreach ($name in $endpointsByName.get_Keys()) {
        $endpoints = @($endpointsByName[$name] | Sort-Object)
        $findings.Add([PSCustomObject]@{
                Name               = $name
                EndpointCount      = $endpoints.Count
                Endpoints          = $endpoints
                QueryEndpointCount = if ($queryCountByName.ContainsKey($name)) { $queryCountByName[$name] } else { 0 }
                BodyEndpointCount  = if ($bodyCountByName.ContainsKey($name)) { $bodyCountByName[$name] } else { 0 }
            })
    }

    return @($findings | Sort-Object -Property @{ Expression = 'EndpointCount'; Descending = $true }, Name)
}

function Get-PfbWireNameCmdletCounts {
    <#
    .SYNOPSIS
        Wire name -> the distinct set of cmdlets across the WHOLE module that already
        expose it as a resolved ('Typed') parameter -- the raw data
        Get-PfbConventionStrength ranks names against. Built directly from
        Get-PfbCmdletParameterInventory's own output (tools/lib/PfbCmdletParamTools.ps1);
        this function does not re-derive wire-name resolution itself, per this task's
        brief ("read that file to find the right existing data source rather than
        re-deriving wire-name resolution from scratch").
    .OUTPUTS
        System.Collections.Generic.Dictionary[string, System.Collections.Generic.HashSet[string]]
        -- typed Dictionary, not a plain Hashtable, for the same keys-shadowing reason as
        every other new map in this section (a wire name literally named 'keys' is real:
        see Get-PfbParameterCoverageGaps's own comment for the confirmed example).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [AllowEmptyCollection()]
        [object[]]$CmdletInventory
    )

    $map = [System.Collections.Generic.Dictionary[string, object]]::new()
    foreach ($row in $CmdletInventory) {
        if ($row.Surface -ne 'Typed' -or -not $row.WireName) { continue }
        if (-not $map.ContainsKey($row.WireName)) { $map[$row.WireName] = [System.Collections.Generic.HashSet[string]]::new() }
        [void]$map[$row.WireName].Add($row.Cmdlet)
    }
    return $map
}

function Get-PfbConventionStrength {
    <#
    .SYNOPSIS
        Decision 8: for each of -Names (typically the field names Get-PfbSystemicGaps just
        surfaced), how many DISTINCT cmdlets across the whole module already expose that
        exact wire name as a resolved ('Typed') parameter somewhere -- a proxy for "how
        mechanical would it be to close the REMAINING gaps for this name". A name already
        used by hundreds of cmdlets (e.g. `names`) is a trivial batch fix on whatever
        stragglers are left; a name used by ZERO cmdlets (e.g. `context_names`) has no
        established convention to extend at all -- closing it is an architectural
        decision, not a mechanical batch job.
    .OUTPUTS
        [PSCustomObject]@{ Name; CmdletCount; Cmdlets }[], one entry per -Names input IN
        THE SAME ORDER (never re-sorted here -- a caller ranks by CmdletCount itself).
        CmdletCount is 0 and Cmdlets is an empty array (never omitted, never $null) for a
        name no cmdlet exposes at all -- that zero IS the finding for names like
        `context_names`.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [AllowEmptyCollection()]
        [object[]]$CmdletInventory,

        [Parameter(Mandatory)]
        [string[]]$Names
    )

    $countsByName = Get-PfbWireNameCmdletCounts -CmdletInventory $CmdletInventory

    foreach ($name in $Names) {
        $cmdlets = if ($countsByName.ContainsKey($name)) { @($countsByName[$name] | Sort-Object) } else { @() }
        [PSCustomObject]@{
            Name        = $name
            CmdletCount = $cmdlets.Count
            Cmdlets     = $cmdlets
        }
    }
}

function Get-PfbDriftAnnotations {
    <#
    .SYNOPSIS
        Loads docs/drift-annotations.json -- ONE annotation channel serving three purposes
        at once: a recorded design decision (`context_names`/`allow_errors`, both pointing
        at docs/design/fusion-context-injection.md -- a forward reference to a NOT-YET-
        WRITTEN design doc from a separate, related Fusion effort; this function does not
        create that file, only references its path), a prior investigation conclusion, and
        a live-testing hazard note (`management-access-policies`'
        POST/PATCH/DELETE-return-403 finding). Deliberately checked in under docs/
        (tracked by git) and NOT under Data/ -- Data/ is strictly runtime-loaded by
        Private/, and nothing under Private/ may ever wire this file's content into the
        module at runtime; this is a tools/reporting-only concern.
    .DESCRIPTION
        Schema (see docs/drift-annotations.json's own top-level "schema" field for the same
        description kept next to the data):
          {
            "schemaVersion": 1,
            "annotations": [
              {
                "matchType": "field" | "endpoint",
                "match": string,
                    -- exact wire-field name for matchType 'field' (e.g. "context_names");
                       an endpoint-key SUBSTRING for matchType 'endpoint', matched
                       case-insensitively against the "<METHOD> /<path>" key format (e.g.
                       "management-access-policies" matches every method on that resource).
                "kind": "designDecision" | "priorConclusion" | "liveTestingHazard",
                "note": string,
                    -- human-readable, deliberately never a machine-verified assertion.
                       E.g. allow_errors' note says only "not yet implemented" -- NOT
                       whether its injection would be gated on the endpoint declaring the
                       parameter or sent unconditionally to every endpoint. That specific
                       behavioral question is explicitly deferred to a separate PR (#22)
                       and is not yet decided; this file must never assert either answer.
                "reference": string | null
                    -- a doc path (repo-relative), or null when there's nowhere to point.
              }, ...
            ]
          }
        Easy to extend: append another object to "annotations" -- no code change needed for
        a new entry with an existing "kind"/"matchType" value.
    .OUTPUTS
        The parsed PSCustomObject (schemaVersion/annotations), or $null if -Path doesn't
        exist. Never throws for a missing file -- an absent annotations file means "no
        annotations available (yet)", not a hard error, so a consumer keeps working even
        before this file existed / if it's ever deleted.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not (Test-Path $Path)) { return $null }
    return Get-Content -Path $Path -Raw | ConvertFrom-Json -Depth 10
}

function Find-PfbDriftAnnotation {
    <#
    .SYNOPSIS
        Looks up every annotation in -Annotations (Get-PfbDriftAnnotations's output) that
        matches -FieldName (matchType 'field', exact match) and/or -Endpoint (matchType
        'endpoint', case-insensitive substring match against the endpoint key).
    .OUTPUTS
        [PSCustomObject][] -- zero or more matching annotation records, never $null (an
        empty array when -Annotations is $null, has no "annotations" list, or nothing
        matches).
    #>
    [CmdletBinding()]
    param(
        [AllowNull()]
        $Annotations,

        [string]$FieldName,

        [string]$Endpoint
    )

    if (-not $Annotations -or -not $Annotations.annotations) { return @() }

    return @($Annotations.annotations | Where-Object {
            ($_.matchType -eq 'field' -and $FieldName -and $_.match -eq $FieldName) -or
            ($_.matchType -eq 'endpoint' -and $Endpoint -and $Endpoint -like "*$($_.match)*")
        })
}

function Test-PfbExpressionReferencesParameter {
    <#
    .SYNOPSIS
        Internal helper for Get-PfbCentralInjectionSites: true if -ExpressionAst references,
        ANYWHERE within its subtree, a variable whose name is in -ParameterNames (the
        enclosing function's own declared parameter names) -- e.g. `$BoundParameters['Filter']`
        references `$BoundParameters`, or `$Names -join ','` references `$Names`.
    .OUTPUTS
        [bool]
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.Management.Automation.Language.Ast]$ExpressionAst,

        [Parameter(Mandatory)]
        [System.Collections.Generic.HashSet[string]]$ParameterNames
    )

    if ($ParameterNames.Count -eq 0) { return $false }

    $varRefs = $ExpressionAst.FindAll({ param($n) $n -is [System.Management.Automation.Language.VariableExpressionAst] }, $true)
    foreach ($v in $varRefs) {
        if ($ParameterNames.Contains($v.VariablePath.UserPath)) { return $true }
    }
    return $false
}

function Test-PfbGuardedByParameterCondition {
    <#
    .SYNOPSIS
        Internal helper for Get-PfbCentralInjectionSites: true if -Assignment sits inside an
        enclosing `if` clause whose test expression, taken AS A WHOLE, is EXACTLY a bare
        parameter reference (`if ($Names)`) or a `.ContainsKey(...)` call on a parameter
        (`if ($BoundParameters.ContainsKey('TotalOnly'))`) -- the two guard shapes
        Private/Add-PfbCommonQueryParams.ps1 actually uses.
    .DESCRIPTION
        Deliberately narrow, not "the condition mentions a parameter anywhere": a condition
        that merely INCLUDES a parameter as one operand of a larger boolean expression --
        e.g. Private/Invoke-PfbApiRequest.ps1's `$AutoPaginate -and $response.continuation_token
        -and -not $limitReached` -- does NOT match here, because $AutoPaginate there gates
        WHETHER pagination happens at all, not WHERE the assigned key's VALUE comes from.
        Only a condition that reduces, whole, to one of the two exact shapes above counts,
        matching the real Add-PfbCommonQueryParams idiom this rule exists to recognize.
    .OUTPUTS
        [bool]
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.Management.Automation.Language.Ast]$Assignment,

        [Parameter(Mandatory)]
        [System.Collections.Generic.HashSet[string]]$ParameterNames
    )

    if ($ParameterNames.Count -eq 0) { return $false }

    $node = $Assignment.Parent
    while ($node) {
        if ($node -is [System.Management.Automation.Language.IfStatementAst]) {
            foreach ($clause in $node.Clauses) {
                $withinBody = @($clause.Item2.FindAll({ param($n) $n -eq $Assignment }, $true))
                if ($withinBody.Count -eq 0) { continue }

                # Unwrap the PipelineAst/CommandExpressionAst layers the parser puts around
                # a bare `if (...)` test expression -- same wrapping phenomenon
                # Resolve-PfbSingleExpression (tools/lib/PfbCmdletParamTools.ps1) already
                # peels for an assignment's right-hand side, reused here rather than
                # re-deriving the same unwrap loop.
                $condExpr = Resolve-PfbSingleExpression -Ast $clause.Item1

                $bareVar = $condExpr -as [System.Management.Automation.Language.VariableExpressionAst]
                if ($bareVar -and $ParameterNames.Contains($bareVar.VariablePath.UserPath)) { return $true }

                $memberCall = $condExpr -as [System.Management.Automation.Language.InvokeMemberExpressionAst]
                if ($memberCall -and $memberCall.Member -is [System.Management.Automation.Language.StringConstantExpressionAst] -and
                    $memberCall.Member.Value -eq 'ContainsKey') {
                    $callTarget = $memberCall.Expression -as [System.Management.Automation.Language.VariableExpressionAst]
                    if ($callTarget -and $ParameterNames.Contains($callTarget.VariablePath.UserPath)) { return $true }
                }
            }
        }
        $node = $node.Parent
    }
    return $false
}

function Get-PfbCentralInjectionSites {
    <#
    .SYNOPSIS
        Scans every function in -PrivateDirectory for the same wire-key assignment AST
        shape Get-PfbWireNameForParameter (tools/lib/PfbCmdletParamTools.ps1) already
        recognizes for Public/ cmdlets -- `$Var['key'] = <rhs>`, an IndexExpressionAst on
        the assignment's left side -- restricted to the three variable names this module
        actually uses, Private-side, for a request's wire-level payload hashtable:
        'queryParams' (Invoke-PfbApiRequest's own -QueryParams parameter), 'body' (its
        -Body parameter), and 'into' (Add-PfbCommonQueryParams's -Into parameter, the
        query-params hashtable a Public/ caller passes in by reference).
    .DESCRIPTION
        Deliberately narrower than "every IndexExpressionAst assignment anywhere in
        Private/": this directory also splats plenty of OTHER hashtables that are
        HTTP-transport/SSH plumbing, never spec-documented API fields -- $headers,
        $restParams, $sshParams, $loginParams, $jwtParams, $oauthParams (confirmed by
        direct inspection: Private/Invoke-PfbApiRequest.ps1, Private/Get-PfbApiTokenViaSsh.ps1,
        Private/Invoke-PfbApiTokenLogin.ps1, Private/Invoke-PfbOAuth2Login.ps1). Including
        those would pollute the candidate list with junk like 'Authorization' or
        'AcceptKey' that could never be a capability-map field name in the first place.

        For each matching assignment, classifies whether the assigned VALUE traces back to
        a parameter of the ENCLOSING function:
          - directly, via Test-PfbExpressionReferencesParameter on the right-hand side
            (e.g. `$Into['filter'] = $BoundParameters['Filter']` references $BoundParameters,
            a parameter of Add-PfbCommonQueryParams; `$Into['names'] = $Names -join ','`
            references $Names directly); or
          - via Test-PfbGuardedByParameterCondition, for the one real case where the
            right-hand side is a bare literal but the key's PRESENCE is still gated on a
            parameter (`if ($BoundParameters.ContainsKey('TotalOnly')) { $Into['total_only'] = 'true' }`).
        Anything neither reaches is classified 'server-or-internal-derived' -- e.g.
        Private/Invoke-PfbApiRequest.ps1's own
        `$QueryParams['continuation_token'] = $response.continuation_token`: its RHS
        references `$response` (not a declared parameter of Invoke-PfbApiRequest), and its
        guard condition (`$AutoPaginate -and $response.continuation_token -and -not
        $limitReached`) is a compound `-and` expression, not one of
        Test-PfbGuardedByParameterCondition's two narrow whole-condition shapes, so it does
        not get credited to $AutoPaginate merely because that parameter happens to appear
        in it.

        This is intentionally narrow, not general symbolic data-flow analysis. See this
        function's own Caveat output field (always populated) for the resulting COVERAGE
        (never correctness) claim: this AST scan cannot verify injection ORDERING relative
        to Assert-PfbApiCapability (the module's actual parameter-support gate) -- an
        assignment could in principle run before or after that gate in a way this scan
        does not model.
    .OUTPUTS
        [PSCustomObject]@{ Key; File; Function; Line; TargetVariable; ParameterTraced;
        Classification; Caveat }[] -- Classification is 'parameter-sourced' (traces to a
        cmdlet/caller parameter; must NEVER become a candidate for
        $script:PfbNonActionableParameters) or 'server-or-internal-derived' (a candidate --
        see Get-PfbDerivedNonActionableParameters for how candidates are reduced to a final
        per-key verdict).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$PrivateDirectory
    )

    $targetVarNames = @('queryparams', 'body', 'into')
    $coverageCaveat = 'coverage claim only -- this AST scan cannot verify injection ordering relative to Assert-PfbApiCapability'

    $results = [System.Collections.Generic.List[object]]::new()
    $files = Get-ChildItem -Path $PrivateDirectory -Filter '*.ps1' -Recurse -File

    foreach ($file in $files) {
        $tokens = $null; $parseErrors = $null
        $ast = [System.Management.Automation.Language.Parser]::ParseFile($file.FullName, [ref]$tokens, [ref]$parseErrors)
        $functionAsts = $ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)

        foreach ($funcAst in $functionAsts) {
            $paramBlock = $funcAst.Body.ParamBlock
            $paramNames = [System.Collections.Generic.HashSet[string]]::new([string[]]@(), [System.StringComparer]::OrdinalIgnoreCase)
            if ($paramBlock) {
                foreach ($p in $paramBlock.Parameters) { [void]$paramNames.Add($p.Name.VariablePath.UserPath) }
            }

            $assignments = $funcAst.FindAll({
                    param($n)
                    $n -is [System.Management.Automation.Language.AssignmentStatementAst] -and
                    $n.Left -is [System.Management.Automation.Language.IndexExpressionAst]
                }, $true)

            foreach ($assign in $assignments) {
                $indexExpr = $assign.Left
                $targetVar = $indexExpr.Target -as [System.Management.Automation.Language.VariableExpressionAst]
                if (-not $targetVar) { continue }
                if ($targetVarNames -notcontains $targetVar.VariablePath.UserPath.ToLowerInvariant()) { continue }

                $keyExpr = $indexExpr.Index -as [System.Management.Automation.Language.StringConstantExpressionAst]
                if (-not $keyExpr) { continue }

                $rhsTraced = Test-PfbExpressionReferencesParameter -ExpressionAst $assign.Right -ParameterNames $paramNames
                $conditionTraced = Test-PfbGuardedByParameterCondition -Assignment $assign -ParameterNames $paramNames
                $traced = $rhsTraced -or $conditionTraced
                $classification = if ($traced) { 'parameter-sourced' } else { 'server-or-internal-derived' }

                $results.Add([PSCustomObject]@{
                        Key             = $keyExpr.Value
                        File            = $file.FullName
                        Function        = $funcAst.Name
                        Line            = $assign.Extent.StartLineNumber
                        TargetVariable  = $targetVar.VariablePath.UserPath
                        ParameterTraced = $traced
                        Classification  = $classification
                        Caveat          = $coverageCaveat
                    })
            }
        }
    }

    return $results.ToArray()
}

function Get-PfbDerivedNonActionableParameters {
    <#
    .SYNOPSIS
        Reduces Get-PfbCentralInjectionSites's per-assignment-site output to one verdict
        per distinct wire key: a key becomes a DERIVED non-actionable-parameter candidate
        only when EVERY assignment site found for that key classified
        'server-or-internal-derived' -- if even ONE site for the same key traces to a
        parameter (as filter/sort/limit/total_only/names/ids all do, via
        Private/Add-PfbCommonQueryParams.ps1), the key is excluded from this result, never
        silently added. Excluding those six would be actively harmful, not just imprecise:
        it would silently delete real, still-open gaps on every endpoint/cmdlet that
        doesn't yet expose that parameter (measured against the real capability map: 160
        genuine residual gaps across the six names combined -- 13+35+14+17+35+46).
    .OUTPUTS
        [PSCustomObject]@{ Name; Sites; Caveat; Strength }[], sorted by Name.
        Strength is 'structural' for `continuation_token` specifically (its RHS is
        provably server-response state, `$response.continuation_token` in
        Private/Invoke-PfbApiRequest.ps1 -- can never be sourced from a cmdlet parameter
        even in principle, not merely "not currently seen as a gap") and 'coverage' for
        every other derived key (the general case -- this scan can only claim no OTHER
        Private/ assignment for that key traced to a parameter; it is a coverage claim,
        never a correctness one, per Get-PfbCentralInjectionSites's own Caveat).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [AllowEmptyCollection()]
        [object[]]$InjectionSites
    )

    $byKey = $InjectionSites | Group-Object -Property Key

    $results = [System.Collections.Generic.List[object]]::new()
    foreach ($group in $byKey) {
        $sites = @($group.Group)
        $anyParameterSourced = [bool]($sites | Where-Object { $_.Classification -eq 'parameter-sourced' })
        if ($anyParameterSourced) { continue }

        $strength = if ($group.Name -eq 'continuation_token') { 'structural' } else { 'coverage' }

        $results.Add([PSCustomObject]@{
                Name     = $group.Name
                Sites    = $sites
                Caveat   = $sites[0].Caveat
                Strength = $strength
            })
    }

    return @($results | Sort-Object Name)
}

function Get-PfbNonActionableParameters {
    <#
    .SYNOPSIS
        The full, up-to-date replacement for reading $script:PfbNonActionableParameters
        directly: the two structurally-confirmed-absent hardcoded entries (X-Request-ID,
        offset -- see the comment above $script:PfbNonActionableParameters for why no
        injection site exists for either) UNIONED with whatever
        Get-PfbCentralInjectionSites/Get-PfbDerivedNonActionableParameters currently derive
        from the real -PrivateDirectory tree -- today, exactly 'continuation_token'.
    .DESCRIPTION
        Callers (e.g. tools/Build-PfbApiDriftReport.ps1's -ExcludedFields) should call this
        function instead of reading $script:PfbNonActionableParameters directly, so a
        future change to Private/Invoke-PfbApiRequest.ps1's injection shape -- e.g. if it
        stopped injecting continuation_token, or started sourcing it from a parameter
        instead of $response -- is reflected automatically the next time this runs, rather
        than silently going stale the way the old hand-written comment could.
    .OUTPUTS
        string[], sorted, deduplicated.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$PrivateDirectory
    )

    # @(...) wraps BOTH calls, not just the final consumption -- the same "assigning a
    # function's output straight to a variable silently collapses a ZERO-element result to
    # $null, not a real empty array/collection" hazard already documented repeatedly
    # elsewhere in this file (e.g. Get-PfbParameterCoverageGaps's $readOnlyList comment).
    # -InjectionSites/-InjectionSites below both carry [AllowEmptyCollection()], which
    # accepts a real empty array but still rejects an outright $null -- confirmed live: a
    # -PrivateDirectory tree with zero matching assignment sites made
    # Get-PfbCentralInjectionSites's `return $results.ToArray()` collapse to $null on
    # assignment here, throwing a ParameterBindingValidationException one call downstream.
    $sites = @(Get-PfbCentralInjectionSites -PrivateDirectory $PrivateDirectory)
    $derived = @(Get-PfbDerivedNonActionableParameters -InjectionSites $sites)
    $derivedNames = @($derived | ForEach-Object { $_.Name })

    return @($script:PfbNonActionableParameters + $derivedNames | Select-Object -Unique | Sort-Object)
}
