#Requires -Version 5.1
<#
.SYNOPSIS
    The pure half of the drift -> GitHub issue reconciler (tools/New-PfbDriftIssue.ps1).
.DESCRIPTION
    Turns Reports/PfbApiDriftReport.json and Reports/PfbDeadKeyReport.json into one
    fingerprinted finding per atomic gap, groups the findings into issue-sized units, and
    plans the issue writes that reconcile them with what GitHub already holds.

    Nothing here touches the network or the filesystem. The shell script owns every read
    and write, so each rule below is testable against in-memory fixtures
    (Tests/PfbDriftIssueTools.Tests.ps1) with no token and no repository.

    THE FINGERPRINT IS A PUBLIC, PERMANENT KEY. It is stamped into issue bodies on
    github.com, closed issues included, and GitHub issues are the reconciler's only state --
    there is no baseline file. Changing the tuple, a category token, the separator or the
    hash re-keys every stamped issue at once: every open issue's findings "vanish" (the
    restructure guard then aborts every run) and every declined finding becomes eligible to
    be filed again. Treat $script:PfbDriftCategoryToken and Get-PfbDriftFingerprint as
    frozen; the golden values in the test file exist to make an accidental change red.

    5.1-compatible for the same reason as tools/lib/PfbAgentBriefTools.ps1: nothing here
    needs 7, and claiming 7 would make the test file skip on the winps51 leg, which the
    coverage gate would then require to be pinned in Tests/coverage-baseline.psd1.
    Pure ASCII on purpose: PSUseBOMForUnicodeEncodedFile is held at zero repo-wide.
#>

# Category tokens. PART OF THE FINGERPRINT -- see the note above before touching one.
$script:PfbDriftCategoryToken = @(
    'deadKey'
    'noSurvivingSelector'
    'responseFieldRemoval'
    'responseFieldRename'
    'validateSetDrift'
    'uncoveredEndpoint'
    'unhandledEnvelopeField'
    'parameterGap'
    'newValidateSetCandidate'
)

# Lower is more severe. Orders creation under -MaxCreate and picks the area: label.
# Correctness defects first (a dead key sends something the array ignores; a removed or
# renamed response field breaks callers; a stale ValidateSet rejects legal values), then
# missing surface (an uncovered endpoint, an unread envelope field, a missing parameter),
# then an ergonomic suggestion last.
$script:PfbDriftSeverity = @{
    deadKey                 = 1
    noSurvivingSelector     = 1
    responseFieldRemoval    = 2
    responseFieldRename     = 3
    validateSetDrift        = 4
    uncoveredEndpoint       = 5
    unhandledEnvelopeField  = 6
    parameterGap            = 7
    newValidateSetCandidate = 8
}

$script:PfbDriftSystemicFamilyThreshold = 3
$script:PfbDriftVanishThreshold = 0.25

# GitHub rejects an issue body over 65,536 characters; this leaves headroom.
$script:PfbDriftBodyLimit = 60000

$script:PfbDriftGroupKeyPattern = '^(family|systemic|envelope|validateset|deadkey|reopen):[A-Za-z0-9_.-]+$'

$script:PfbDriftDisclaimer = '> *Generated by automation: `tools/New-PfbDriftIssue.ps1`, reconciling the committed drift reports. No person reviewed this text before it was posted.*'

$script:PfbDriftLabel = @{
    Source   = 'source:drift'
    Triage   = 'status:triage'
    LiveTest = 'needs:live-test'
    Coverage = 'area:cmdlet-coverage'
    Wire     = 'area:wire-contract'
    Resolved = 'status:resolved-upstream'
}

$script:PfbDriftReportRequiredProperty = @(
    'schemaVersion'
    'uncoveredEndpoints'
    'parameterGaps'
    'validateSetDrift'
    'newValidateSetCandidates'
    'responseFieldRemovals'
    'responseFieldRenameCandidates'
    'unhandledResponseEnvelopeFields'
)
$script:PfbDeadKeyReportRequiredProperty = @('deadKeys', 'noSurvivingSelector')

function Get-PfbDriftItem {
    <#
    .SYNOPSIS
        The non-null elements of a report or issue collection.
    .DESCRIPTION
        @($x) on a JSON null is a ONE-element array holding $null, so iterating a property
        that is null rather than [] would hand every loop body a $null row. Wrap every
        collection read from a report or from gh in this before iterating it, and wrap the
        call in @().
    #>
    [CmdletBinding()]
    param([Parameter(Position = 0)][AllowNull()]$Value)

    foreach ($item in @($Value)) {
        if ($null -ne $item) { $item }
    }
}

function Get-PfbDriftSortedString {
    <#
    .SYNOPSIS
        Ordinal, de-duplicated sort of a string list.
    .DESCRIPTION
        Sort-Object is culture-aware, and the two editions this repo gates on disagree on
        invariant linguistic order (5.1 ignores hyphens when collating; 7 does not). A
        fingerprint list sorted with it would reorder between editions and every machine
        block would churn. Ordinal comparison is identical on both. Same reasoning as
        Sort-PfbSelectorString in tools/lib/PfbPipelineSelectorTools.ps1, which cannot be
        reused: that file is PowerShell 7 only and its verb is unapproved.
    .OUTPUTS
        [string] -- one element at a time; wrap the call in @().
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Position = 0)][AllowNull()][AllowEmptyCollection()][string[]]$Value)

    $set = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    foreach ($item in @($Value)) {
        if ($null -ne $item) { [void]$set.Add($item) }
    }
    $list = [System.Collections.Generic.List[string]]::new($set)
    $list.Sort([System.StringComparer]::Ordinal)
    foreach ($item in $list) { $item }
}

function ConvertTo-PfbDriftEndpoint {
    <#
    .SYNOPSIS
        Normalises an endpoint to the 'METHOD /path' form fingerprints are computed over.
    .DESCRIPTION
        The drift report writes 'GET /alerts'; the dead-key report writes method 'GET' and
        endpoint 'alerts' separately, with no leading slash. Both must produce one string,
        or the same gap would carry two fingerprints depending on which report found it.
    #>
    [CmdletBinding(DefaultParameterSetName = 'Key')]
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true, ParameterSetName = 'Key')][string]$Endpoint,
        [Parameter(Mandatory = $true, ParameterSetName = 'Parts')][string]$Method,
        [Parameter(Mandatory = $true, ParameterSetName = 'Parts')][string]$Path
    )

    if ($PSCmdlet.ParameterSetName -eq 'Key') {
        $parts = $Endpoint.Trim() -split '\s+', 2
        if ($parts.Count -ne 2) { throw "Endpoint '$Endpoint' is not in 'METHOD /path' form." }
        $Method = $parts[0]
        $Path = $parts[1]
    }

    $verb = $Method.Trim().ToUpperInvariant()
    if ($verb -cnotmatch '^[A-Z]+$') { throw "'$Method' is not an HTTP method." }
    $trimmed = $Path.Trim().Trim('/')
    if ($trimmed -eq '' -or $trimmed -match '\s' -or $trimmed.Contains('|')) {
        throw "Path '$Path' cannot be normalised into an endpoint."
    }
    return ('{0} /{1}' -f $verb, $trimmed)
}

function Get-PfbDriftFamily {
    <#
    .SYNOPSIS
        The endpoint family: the first path segment of a 'METHOD /path' endpoint.
    .DESCRIPTION
        Matches Get-PfbSelectorProducerIndex in tools/lib/PfbPipelineSelectorTools.ps1:
        split on the first space, trim the leading slash, take the first '/' segment.
        Re-implemented rather than shared because that file is PowerShell 7 only.
        'GET /api/login-banner' is family 'api'. A finding with no endpoint has family ''.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory = $true)][AllowEmptyString()][string]$Endpoint)

    if ($Endpoint -eq '') { return '' }
    $parts = $Endpoint -split ' ', 2
    if ($parts.Count -ne 2) { throw "Endpoint '$Endpoint' is not in 'METHOD /path' form." }
    return (($parts[1].TrimStart('/')) -split '/')[0]
}

function Get-PfbDriftFingerprint {
    <#
    .SYNOPSIS
        sha256('<category>|<METHOD /path>|<field>'), first 16 lowercase hex characters.
    .DESCRIPTION
        No version component, so a finding keeps its fingerprint across spec releases. The
        per-category tuple is documented in tools/README.md; an absent component is the
        empty string, never omitted, so 'uncoveredEndpoint|GET /x|' keeps both separators.
        FROZEN -- see the note at the top of this file.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)][string]$Category,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$Endpoint,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$Field
    )

    if ($script:PfbDriftCategoryToken -cnotcontains $Category) {
        throw "'$Category' is not a drift category token ($($script:PfbDriftCategoryToken -join ', '))."
    }
    if ($Endpoint.Contains('|') -or $Field.Contains('|')) {
        throw "'|' is the fingerprint separator and cannot appear in an endpoint or field ('$Endpoint', '$Field')."
    }

    $text = '{0}|{1}|{2}' -f $Category, $Endpoint, $Field
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = $sha.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($text))
    }
    finally {
        $sha.Dispose()
    }
    $hex = -join ($bytes | ForEach-Object { $_.ToString('x2') })
    return $hex.Substring(0, 16)
}

function ConvertTo-PfbDriftFindingRecord {
    <#
    .SYNOPSIS
        Builds one finding record. The only constructor, so every finding has one shape.
    .DESCRIPTION
        A Field holding '@{' or whitespace throws. Both are what PowerShell makes of an
        object or an array cast to [string] ('@{name=ids}', 'a b'), and a report that changed
        a list from strings to objects would otherwise be fingerprinted as garbage and
        stamped into issues -- where the frozen tuple means it can never be re-keyed.
    .OUTPUTS
        [PSCustomObject] Category, Endpoint, Field, Family, Parameter, Cmdlet, GroupKey
        ($null until Get-PfbDriftGroup), Fingerprint, Severity, Detail.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][string]$Category,
        [AllowEmptyString()][string]$Endpoint = '',
        [AllowEmptyString()][string]$Field = '',
        [AllowEmptyString()][string]$Parameter = '',
        [AllowEmptyString()][string]$Cmdlet = '',
        [Parameter(Mandatory = $true)][hashtable]$Detail
    )

    if ($Field.Contains('@{') -or $Field -match '\s') {
        throw "A $Category finding on '$Endpoint' has field '$Field', which looks like a stringified object or carries whitespace. The report's shape has probably changed; fix the reader before fingerprinting it, because a fingerprint is stamped into issues for good."
    }
    $normalised = ''
    if ($Endpoint -ne '') { $normalised = ConvertTo-PfbDriftEndpoint -Endpoint $Endpoint }
    return [PSCustomObject]@{
        Category    = $Category
        Endpoint    = $normalised
        Field       = $Field
        Family      = (Get-PfbDriftFamily -Endpoint $normalised)
        Parameter   = $Parameter
        Cmdlet      = $Cmdlet
        GroupKey    = $null
        Fingerprint = (Get-PfbDriftFingerprint -Category $Category -Endpoint $normalised -Field $Field)
        Severity    = [int]$script:PfbDriftSeverity[$Category]
        Detail      = [PSCustomObject]$Detail
    }
}

function Get-PfbDriftFinding {
    <#
    .SYNOPSIS
        Flattens both reports into one finding per atomic gap, grouped and fingerprinted.
    .DESCRIPTION
        Categories read, and the fingerprint tuple each produces:

          uncoveredEndpoints              uncoveredEndpoint        <endpoint>  ''
          parameterGaps (per param)       parameterGap             <endpoint>  query:<name> | body:<name>
          responseFieldRemovals           responseFieldRemoval     <endpoint>  <location>:<field>
          responseFieldRenameCandidates   responseFieldRename      <endpoint>  <location>:<from>-><to>
          validateSetDrift (per value)    validateSetDrift         ''          <cmdlet>:<param>=missing:<v> | =stale:<v>
          newValidateSetCandidates        newValidateSetCandidate  ''          <cmdlet>:<param>
          unhandledResponseEnvelopeFields unhandledEnvelopeField   ''          <field>
          deadKeys                        deadKey                  <endpoint>  <wireKey>
          noSurvivingSelector             noSurvivingSelector      <endpoint>  ''

        Deliberately NOT read: readOnlyFields (the report lists them "for completeness
        only" -- no cmdlet can ever set one), systemicGaps (an aggregate whose every
        endpoint x name pair is already a parameterGaps entry; the systemic grouping is
        recomputed from the atoms in Get-PfbDriftGroup), conventionStrength and
        contextCardinality (not findings).

        A missing category property throws instead of reading as zero findings: zero
        findings would make every open drift issue look resolved.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]$DriftReport,
        [Parameter(Mandatory = $true)]$DeadKeyReport
    )

    $driftNames = @($DriftReport.PSObject.Properties | ForEach-Object { $_.Name })
    $missing = @($script:PfbDriftReportRequiredProperty | Where-Object { $driftNames -cnotcontains $_ })
    if ($missing.Count -gt 0) {
        throw "The drift report has no $($missing -join ', ') property. A renamed or removed category would otherwise read as zero findings and make every open drift issue look resolved."
    }
    if ([string]$DriftReport.schemaVersion -ne '1') {
        throw "The drift report is schemaVersion $($DriftReport.schemaVersion); this reconciler understands 1. Review the category shapes before raising it."
    }
    $deadNames = @($DeadKeyReport.PSObject.Properties | ForEach-Object { $_.Name })
    $missing = @($script:PfbDeadKeyReportRequiredProperty | Where-Object { $deadNames -cnotcontains $_ })
    if ($missing.Count -gt 0) {
        throw "The dead-key report has no $($missing -join ', ') property."
    }

    $records = [System.Collections.Generic.List[object]]::new()

    foreach ($row in @(Get-PfbDriftItem $DriftReport.uncoveredEndpoints)) {
        $records.Add((ConvertTo-PfbDriftFindingRecord -Category 'uncoveredEndpoint' -Endpoint $row.endpoint -Detail @{
                    MinVersion = [string]$row.minVersion
                }))
    }

    foreach ($row in @(Get-PfbDriftItem $DriftReport.parameterGaps)) {
        $cmdlets = @(Get-PfbDriftSortedString -Value @(Get-PfbDriftItem $row.cmdlets))
        $level = ''
        $caveat = ''
        if ($null -ne $row.confidence) {
            $level = [string]$row.confidence.level
            $caveat = [string]$row.confidence.caveat
        }
        $notes = @(@(Get-PfbDriftItem $row.annotations) | ForEach-Object { '{0}: {1}' -f $_.kind, $_.note })

        $names = [System.Collections.Generic.List[object]]::new()
        foreach ($entry in @(Get-PfbDriftItem $row.missingQueryParameters)) {
            # Bare strings in every committed report so far, but read the object shape too:
            # missingBodyProperties already moved to it, and a query list that followed would
            # otherwise stringify each entry into a garbage field such as 'query:@{name=ids}'.
            if ($entry -is [string]) { $names.Add(@('query', $entry)) }
            else { $names.Add(@('query', [string]$entry.name)) }
        }
        foreach ($entry in @(Get-PfbDriftItem $row.missingBodyProperties)) {
            # Polymorphic in the committed report: an object carrying .name on most rows, a
            # bare string on a few (7 of 354 rows when this was written, e.g. PATCH /file-systems).
            if ($entry -is [string]) { $names.Add(@('body', $entry)) }
            else { $names.Add(@('body', [string]$entry.name)) }
        }
        foreach ($pair in $names) {
            $location = $pair[0]
            $name = $pair[1]
            if ([string]::IsNullOrWhiteSpace($name)) {
                throw "parameterGaps row '$($row.endpoint)' has a $location parameter with no name."
            }
            $records.Add((ConvertTo-PfbDriftFindingRecord -Category 'parameterGap' -Endpoint $row.endpoint `
                        -Field ('{0}:{1}' -f $location, $name) -Parameter $name -Detail @{
                        Location    = $location
                        Cmdlets     = $cmdlets
                        Confidence  = $level
                        Caveat      = $caveat
                        Annotations = $notes
                    }))
        }
    }

    foreach ($row in @(Get-PfbDriftItem $DriftReport.responseFieldRemovals)) {
        $records.Add((ConvertTo-PfbDriftFindingRecord -Category 'responseFieldRemoval' -Endpoint $row.endpoint `
                    -Field ('{0}:{1}' -f $row.location, $row.field) -Detail @{
                    IntroducedVersion = [string]$row.introducedVersion
                    LastSeenVersion   = [string]$row.lastSeenVersion
                }))
    }

    foreach ($row in @(Get-PfbDriftItem $DriftReport.responseFieldRenameCandidates)) {
        $records.Add((ConvertTo-PfbDriftFindingRecord -Category 'responseFieldRename' -Endpoint $row.endpoint `
                    -Field ('{0}:{1}->{2}' -f $row.location, $row.from, $row.to) -Detail @{
                    From    = [string]$row.from
                    To      = [string]$row.to
                    Version = [string]$row.version
                }))
    }

    foreach ($row in @(Get-PfbDriftItem $DriftReport.validateSetDrift)) {
        foreach ($kind in 'missing', 'stale') {
            $values = @(Get-PfbDriftItem $row.missingValues)
            if ($kind -eq 'stale') { $values = @(Get-PfbDriftItem $row.staleValues) }
            foreach ($value in $values) {
                $records.Add((ConvertTo-PfbDriftFindingRecord -Category 'validateSetDrift' -Cmdlet $row.cmdlet `
                            -Field ('{0}:{1}={2}:{3}' -f $row.cmdlet, $row.parameter, $kind, $value) -Detail @{
                            Parameter = [string]$row.parameter
                            Kind      = $kind
                            Value     = [string]$value
                        }))
            }
        }
    }

    foreach ($row in @(Get-PfbDriftItem $DriftReport.newValidateSetCandidates)) {
        $records.Add((ConvertTo-PfbDriftFindingRecord -Category 'newValidateSetCandidate' -Cmdlet $row.cmdlet `
                    -Field ('{0}:{1}' -f $row.cmdlet, $row.parameter) -Detail @{
                    Parameter      = [string]$row.parameter
                    WireName       = [string]$row.wireName
                    SpecValues     = @(Get-PfbDriftItem $row.specValues)
                    Recommendation = [string]$row.recommendation
                }))
    }

    foreach ($row in @(Get-PfbDriftItem $DriftReport.unhandledResponseEnvelopeFields)) {
        $records.Add((ConvertTo-PfbDriftFindingRecord -Category 'unhandledEnvelopeField' -Field ([string]$row.field) -Detail @{
                    EndpointCount = [int]$row.endpointCount
                }))
    }

    foreach ($row in @(Get-PfbDriftItem $DeadKeyReport.deadKeys)) {
        $endpoint = ConvertTo-PfbDriftEndpoint -Method $row.method -Path $row.endpoint
        $records.Add((ConvertTo-PfbDriftFindingRecord -Category 'deadKey' -Endpoint $endpoint -Field ([string]$row.wireKey) -Detail @{
                    Cmdlets        = @([string]$row.cmdlet)
                    Parameters     = @('{0} -{1}' -f $row.cmdlet, $row.parameter)
                    ReportSeverity = [string]$row.severity
                    Classification = [string]$row.classification
                }))
    }

    foreach ($row in @(Get-PfbDriftItem $DeadKeyReport.noSurvivingSelector)) {
        $endpoint = ConvertTo-PfbDriftEndpoint -Method $row.method -Path $row.endpoint
        $records.Add((ConvertTo-PfbDriftFindingRecord -Category 'noSurvivingSelector' -Endpoint $endpoint -Detail @{
                    Cmdlets = @([string]$row.cmdlet)
                }))
    }

    # Two rows with one fingerprint are one gap (e.g. two cmdlets sending the same dead
    # key to the same endpoint): keep the first, and merge the cmdlet lists into it.
    $byFingerprint = [System.Collections.Generic.Dictionary[string, object]]::new([System.StringComparer]::Ordinal)
    foreach ($record in $records) {
        if (-not $byFingerprint.ContainsKey($record.Fingerprint)) {
            $byFingerprint[$record.Fingerprint] = $record
            continue
        }
        $kept = $byFingerprint[$record.Fingerprint]
        foreach ($listName in 'Cmdlets', 'Parameters') {
            if (@($kept.Detail.PSObject.Properties | ForEach-Object { $_.Name }) -ccontains $listName) {
                $kept.Detail.$listName = @(Get-PfbDriftSortedString -Value (@($kept.Detail.$listName) + @($record.Detail.$listName)))
            }
        }
    }

    $findings = @(Get-PfbDriftGroup -Finding @($byFingerprint.Values))
    $index = @{}
    foreach ($finding in $findings) { $index[$finding.Fingerprint] = $finding }
    foreach ($fingerprint in @(Get-PfbDriftSortedString -Value @($index.Keys))) { $index[$fingerprint] }
}

function Get-PfbDriftGroup {
    <#
    .SYNOPSIS
        Sets each finding's GroupKey: the one issue it belongs in.
    .DESCRIPTION
        family:<segment>     uncovered endpoints, response-field removals and renames, and
                             parameter gaps whose parameter is not systemic
        systemic:<param>     parameter gaps for a wire name missing in at least
                             -SystemicFamilyThreshold (3) distinct families, query and body
                             counted together; such a parameter leaves every family group
        envelope:<field>     unhandled response envelope fields
        validateset:<cmdlet> ValidateSet drift and new ValidateSet candidates
        deadkey:<segment>    dead keys and cmdlets with no surviving selector, kept apart
                             from family issues because the fix is remove or relocate

        Grouping decides only where a NEW finding goes. A finding already recorded in an
        open issue stays there even if a later report moves its parameter across the
        systemic threshold -- Get-PfbDriftFindingDisposition checks recorded issues first.

        Mutates GroupKey on the objects it is given, and emits them.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][AllowEmptyCollection()][object[]]$Finding,
        [ValidateRange(1, 1000)][int]$SystemicFamilyThreshold = $script:PfbDriftSystemicFamilyThreshold
    )

    $items = @(Get-PfbDriftItem $Finding)
    $familiesByParameter = [System.Collections.Generic.Dictionary[string, object]]::new([System.StringComparer]::Ordinal)
    foreach ($f in $items) {
        if ($f.Category -cne 'parameterGap') { continue }
        if (-not $familiesByParameter.ContainsKey($f.Parameter)) {
            $familiesByParameter[$f.Parameter] = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
        }
        [void]$familiesByParameter[$f.Parameter].Add($f.Family)
    }

    foreach ($f in $items) {
        switch -CaseSensitive ($f.Category) {
            'parameterGap' {
                if ($familiesByParameter[$f.Parameter].Count -ge $SystemicFamilyThreshold) { $key = 'systemic:' + $f.Parameter }
                else { $key = 'family:' + $f.Family }
            }
            'unhandledEnvelopeField' { $key = 'envelope:' + $f.Field }
            'validateSetDrift' { $key = 'validateset:' + $f.Cmdlet }
            'newValidateSetCandidate' { $key = 'validateset:' + $f.Cmdlet }
            'deadKey' { $key = 'deadkey:' + $f.Family }
            'noSurvivingSelector' { $key = 'deadkey:' + $f.Family }
            default { $key = 'family:' + $f.Family }
        }
        if ($key -cnotmatch $script:PfbDriftGroupKeyPattern) {
            throw "Finding $($f.Fingerprint) ($($f.Category) $($f.Endpoint) $($f.Field)) produced group key '$key', which the machine block cannot carry."
        }
        $f.GroupKey = $key
        $f
    }
}

function Assert-PfbDriftMarker {
    <#
    .SYNOPSIS
        Throws unless a marker object is one the machine block can carry unambiguously.
    #>
    [CmdletBinding()]
    param([Parameter(Mandatory = $true)]$Marker)

    if ($Marker.Kind -cne 'group' -and $Marker.Kind -cne 'paired') {
        throw "A marker's kind is 'group' or 'paired', not '$($Marker.Kind)'."
    }
    if ($Marker.Kind -ceq 'group' -and ([string]$Marker.GroupKey) -cnotmatch $script:PfbDriftGroupKeyPattern) {
        throw "'$($Marker.GroupKey)' is not a drift group key."
    }
    foreach ($fingerprint in (@(Get-PfbDriftItem $Marker.Fingerprints) + @(Get-PfbDriftItem $Marker.Vanished))) {
        if ([string]$fingerprint -cnotmatch '^[0-9a-f]{16}$') {
            throw "'$fingerprint' is not a drift fingerprint (16 lowercase hex characters)."
        }
    }
    $vanished = @(Get-PfbDriftItem $Marker.Vanished)
    $both = @(@(Get-PfbDriftItem $Marker.Fingerprints) | Where-Object { $vanished -ccontains $_ })
    if ($both.Count -gt 0) {
        throw "Fingerprint(s) $($both -join ', ') are recorded as both active and vanished."
    }
}

function Format-PfbDriftMarker {
    <#
    .SYNOPSIS
        Renders a marker as the machine block that ends a drift issue body.
    .DESCRIPTION
        <!-- pfb-drift-block:start -->
        <!-- pfb-drift-group: family:file-systems -->    (or: <!-- pfb-drift-paired: legacy -->)
        <!-- pfb-drift-fingerprints: 0123456789abcdef,... -->
        <!-- pfb-drift-vanished: ... -->                  (only when non-empty)
        <!-- pfb-drift-block:end -->

        Fingerprint lists are emitted ordinally sorted and de-duplicated, so formatting a
        parsed block reproduces it exactly.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)]$Marker,
        [string]$NewLine = "`n"
    )

    if ($NewLine -cne "`n" -and $NewLine -cne "`r`n") { throw '-NewLine is LF or CRLF.' }
    Assert-PfbDriftMarker -Marker $Marker

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('<!-- pfb-drift-block:start -->')
    if ($Marker.Kind -ceq 'group') { $lines.Add("<!-- pfb-drift-group: $($Marker.GroupKey) -->") }
    else { $lines.Add('<!-- pfb-drift-paired: legacy -->') }
    $active = @(Get-PfbDriftSortedString -Value @(Get-PfbDriftItem $Marker.Fingerprints))
    if ($active.Count -gt 0) { $lines.Add("<!-- pfb-drift-fingerprints: $($active -join ',') -->") }
    else { $lines.Add('<!-- pfb-drift-fingerprints: -->') }
    $vanished = @(Get-PfbDriftSortedString -Value @(Get-PfbDriftItem $Marker.Vanished))
    if ($vanished.Count -gt 0) { $lines.Add("<!-- pfb-drift-vanished: $($vanished -join ',') -->") }
    $lines.Add('<!-- pfb-drift-block:end -->')
    return ($lines -join $NewLine)
}

function Get-PfbDriftFenceState {
    <#
    .SYNOPSIS
        Advances CommonMark fenced-code-block state by one line.
    .DESCRIPTION
        State is $null outside a fence, or [PSCustomObject] Char (backtick or tilde) and
        Length (the opener's run length) inside one. Up to 3 leading spaces are stripped.
        Outside a fence, a run of 3+ backticks or 3+ tildes opens one. Inside, only a run of
        the SAME character, at least as long as the opener, followed by nothing but
        whitespace closes it. Every other line leaves the state unchanged.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$Line,
        [AllowNull()]$State
    )

    $tick = [string][char]0x60
    $match = [regex]::Match($Line, '^ {0,3}(?<run>' + $tick + '{3,}|~{3,})(?<rest>.*)$')
    if ($null -eq $State) {
        if (-not $match.Success) { return $null }
        $run = $match.Groups['run'].Value
        return [PSCustomObject]@{ Char = $run.Substring(0, 1); Length = $run.Length }
    }
    if ($match.Success) {
        $run = $match.Groups['run'].Value
        if ($run.Substring(0, 1) -ceq $State.Char -and $run.Length -ge $State.Length -and $match.Groups['rest'].Value.Trim() -eq '') {
            return $null
        }
    }
    return $State
}

function Get-PfbDriftBlockSpan {
    <#
    .SYNOPSIS
        Finds the one pfb-drift block among a body's lines, or reports that there is none.
    .DESCRIPTION
        Lines are compared trimmed, so indentation and a stray CR do not matter. Lines inside
        a fenced code block are skipped, so an issue quoting an example block in a fence is
        not mistaken for a stamped one. Everything malformed throws: this decides which
        issues the reconciler may write to, and guessing would mean rewriting a person's
        text on a misread.

        A start marker inside a fence that is NEVER CLOSED also throws. A person pasting
        output under an opening fence with no closer is a common habit, and it would
        otherwise hide a real block: the issue would look unclaimed, its group would be filed
        a second time, and the rewrite would append a second block. ConvertFrom-PfbDriftIssue
        parses only trusted issues, so this cannot be used to stop a run from outside.
    .OUTPUTS
        $null, or [PSCustomObject] Start, End (line indexes of the delimiters) and Lines
        (the trimmed lines between them).
    #>
    [CmdletBinding()]
    param([Parameter(Mandatory = $true)][AllowEmptyCollection()][AllowEmptyString()][string[]]$Line)

    $fence = $null
    $fenceLine = -1
    $fenceHidesStart = $false
    $start = -1
    $end = -1
    $starts = 0
    $ends = 0
    for ($i = 0; $i -lt $Line.Count; $i++) {
        $text = $Line[$i].Trim()
        $wasInFence = ($null -ne $fence)
        $fence = Get-PfbDriftFenceState -Line $Line[$i] -State $fence
        if ($wasInFence -ne ($null -ne $fence)) {
            if ($null -ne $fence) {
                $fenceLine = $i
                $fenceHidesStart = $false
            }
            continue
        }
        if ($null -ne $fence) {
            if ($text -cmatch '^<!--\s*pfb-drift-block:start\s*-->$') { $fenceHidesStart = $true }
            continue
        }
        if ($text -cmatch '^<!--\s*pfb-drift-block:start\s*-->$') { $starts++; $start = $i; continue }
        if ($text -cmatch '^<!--\s*pfb-drift-block:end\s*-->$') { $ends++; $end = $i; continue }
        $inside = ($starts -eq 1 -and $ends -eq 0)
        if (-not $inside -and $text -cmatch '^<!--\s*pfb-drift-') {
            throw "A pfb-drift marker line sits outside a pfb-drift block: '$text'."
        }
    }

    if (($null -ne $fence) -and $fenceHidesStart) {
        throw "A pfb-drift block start marker sits inside an unterminated code fence (opened on line $($fenceLine + 1)), so it cannot be told apart from a quoted example. Close the fence, or move the block out of it."
    }
    if ($starts -eq 0 -and $ends -eq 0) { return $null }
    if ($starts -ne 1 -or $ends -ne 1) {
        throw "Expected exactly one pfb-drift block; found $starts start and $ends end marker(s)."
    }
    if ($end -lt $start) { throw 'The pfb-drift block end marker comes before its start marker.' }

    $inner = [System.Collections.Generic.List[string]]::new()
    for ($i = $start + 1; $i -lt $end; $i++) { $inner.Add($Line[$i].Trim()) }
    return [PSCustomObject]@{ Start = $start; End = $end; Lines = $inner.ToArray() }
}

function ConvertFrom-PfbDriftMarker {
    <#
    .SYNOPSIS
        Parses the machine block out of an issue body. $null when the body has none.
    .OUTPUTS
        [PSCustomObject] Kind ('group'|'paired'), GroupKey ($null when paired),
        Fingerprints and Vanished (ordinally sorted string arrays).
    #>
    [CmdletBinding()]
    param([Parameter(Mandatory = $true)][AllowNull()][AllowEmptyString()][string]$Body)

    if ([string]::IsNullOrEmpty($Body)) { return $null }
    $lines = ($Body -replace "`r`n", "`n" -replace "`r", "`n") -split "`n"
    $span = Get-PfbDriftBlockSpan -Line $lines
    if ($null -eq $span) { return $null }

    $values = @{}
    foreach ($text in $span.Lines) {
        if ($text -eq '') { continue }
        if (-not ($text -cmatch '^<!--\s*pfb-drift-(?<key>group|paired|fingerprints|vanished):(?<value>.*?)-->$')) {
            throw "Unrecognised line in the pfb-drift block: '$text'."
        }
        $key = $Matches['key']
        if ($values.ContainsKey($key)) { throw "The pfb-drift block has more than one '$key' line." }
        $values[$key] = $Matches['value'].Trim()
    }

    if ($values.ContainsKey('group') -eq $values.ContainsKey('paired')) {
        throw 'A pfb-drift block needs exactly one of a group line or a paired line.'
    }
    if ($values.ContainsKey('paired') -and $values['paired'] -cne 'legacy') {
        throw "A paired line reads 'pfb-drift-paired: legacy', not '$($values['paired'])'."
    }
    if (-not $values.ContainsKey('fingerprints')) { throw 'The pfb-drift block has no fingerprints line.' }

    $vanishedText = ''
    if ($values.ContainsKey('vanished')) { $vanishedText = $values['vanished'] }
    $marker = [PSCustomObject]@{
        Kind         = 'paired'
        GroupKey     = $null
        Fingerprints = @(@($values['fingerprints'] -split ',') | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' })
        Vanished     = @(@($vanishedText -split ',') | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' })
    }
    if ($values.ContainsKey('group')) {
        $marker.Kind = 'group'
        $marker.GroupKey = $values['group']
    }
    Assert-PfbDriftMarker -Marker $marker
    $marker.Fingerprints = @(Get-PfbDriftSortedString -Value $marker.Fingerprints)
    $marker.Vanished = @(Get-PfbDriftSortedString -Value $marker.Vanished)
    return $marker
}

function ConvertTo-PfbDriftIssueBody {
    <#
    .SYNOPSIS
        An issue body with its machine block replaced by -Marker, or appended if absent.
    .DESCRIPTION
        Every character outside the block is preserved exactly -- line endings, trailing
        whitespace, non-ASCII text. This is written back to issues people wrote, so any
        normalisation here would silently edit someone's prose on github.com. The block
        uses the body's own line ending: CRLF if the body contains any CRLF.

        The result is parsed back before it is returned, and must yield exactly -Marker.
        Appending after a person's unclosed code fence, for one, would put the block inside
        the fence; this throws instead of handing back a body whose block does not count.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)][AllowNull()][AllowEmptyString()][string]$Body,
        [Parameter(Mandatory = $true)]$Marker
    )

    if ($null -eq $Body) { $Body = '' }
    $newLine = "`n"
    if ($Body.Contains("`r`n")) { $newLine = "`r`n" }
    $block = Format-PfbDriftMarker -Marker $Marker -NewLine $newLine

    # Split keeping each line's terminator attached, so joining the pieces is lossless.
    $pieces = [regex]::Split($Body, '(?<=\n)')
    $bare = @($pieces | ForEach-Object { $_.TrimEnd([char[]]"`r`n") })
    $span = Get-PfbDriftBlockSpan -Line $bare

    if ($null -eq $span) {
        if ($Body -eq '') { $result = $block }
        else {
            $prefix = $Body
            if (-not $prefix.EndsWith("`n")) { $prefix += $newLine }
            $result = $prefix + $newLine + $block
        }
    }
    else {
        $builder = [System.Text.StringBuilder]::new()
        for ($i = 0; $i -lt $span.Start; $i++) { [void]$builder.Append($pieces[$i]) }
        [void]$builder.Append($block)
        [void]$builder.Append($pieces[$span.End].Substring($bare[$span.End].Length))
        for ($i = $span.End + 1; $i -lt $pieces.Count; $i++) { [void]$builder.Append($pieces[$i]) }
        $result = $builder.ToString()
    }

    $parsed = $null
    $why = 'it holds no block at all'
    try { $parsed = ConvertFrom-PfbDriftMarker -Body $result }
    catch { $why = $_.Exception.Message }
    if ($null -eq $parsed -or (Format-PfbDriftMarker -Marker $parsed) -cne (Format-PfbDriftMarker -Marker $Marker)) {
        if ($null -ne $parsed) { $why = 'it holds a different block' }
        throw "The rewritten body does not parse back to the pfb-drift block just written, so it must not be written: $why"
    }
    return $result
}

function ConvertFrom-PfbDriftIssue {
    <#
    .SYNOPSIS
        Normalises `gh issue list --json number,title,body,state,stateReason,labels` rows.
    .DESCRIPTION
        THE TRUST BOUNDARY. A machine block is read only on an issue labelled source:drift.
        The repository is public: anyone can open an issue, write a valid block into it and
        close it as not planned, which would otherwise decline every finding it lists for
        good, capture a group (so the reconciler edits and comments on a stranger's issue),
        or mark everything tracked. Only collaborators can add labels, so the label is the
        anchor, and gh already returns it. On any other issue the block is ignored entirely
        -- Marker is $null, so it is neither tracked nor declined, and a malformed one does
        not throw (else anyone could stop every run). IgnoredBlock says one was seen.

        On a trusted issue a malformed block throws, naming the issue, before anything is
        planned -- so one hand-edited issue stops the whole run instead of being silently
        skipped or silently rewritten.
    .OUTPUTS
        [PSCustomObject] Number, Title, State ('OPEN'|'CLOSED'), StateReason ('COMPLETED',
        'NOT_PLANNED', 'DUPLICATE', or '' when GitHub recorded none), Labels, Body, Trusted,
        IgnoredBlock, Marker.
    #>
    [CmdletBinding()]
    param([Parameter(Mandatory = $true)][AllowEmptyCollection()][object[]]$Issue)

    foreach ($raw in @(Get-PfbDriftItem $Issue)) {
        $labels = @(@(Get-PfbDriftItem $raw.labels) | ForEach-Object {
                if ($_ -is [string]) { $_ } else { [string]$_.name }
            })
        $body = [string]$raw.body
        $trusted = $labels -ccontains $script:PfbDriftLabel.Source
        $marker = $null
        if ($trusted) {
            try {
                $marker = ConvertFrom-PfbDriftMarker -Body $body
            }
            catch {
                throw "Issue #$($raw.number): $($_.Exception.Message) Fix or remove the block by hand; the reconciler will not guess which findings an issue carries."
            }
        }
        [PSCustomObject]@{
            Number       = [int]$raw.number
            Title        = [string]$raw.title
            State        = ([string]$raw.state).ToUpperInvariant()
            StateReason  = ([string]$raw.stateReason).ToUpperInvariant()
            Labels       = $labels
            Body         = $body
            Trusted      = $trusted
            IgnoredBlock = (-not $trusted) -and $body.Contains('pfb-drift-block:start')
            Marker       = $marker
        }
    }
}

function Format-PfbDriftIssueTitle {
    <#
    .SYNOPSIS
        The title of the issue that carries a group.
    .DESCRIPTION
        Titles are restricted to a character set that survives every hop to gh: ghx is a
        .cmd shim, so cmd.exe would reinterpret & | < > ^ % in an argument, and Windows
        PowerShell 5.1 does not escape an embedded double quote for a native command.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory = $true)][string]$GroupKey)

    $kind, $value = $GroupKey -split ':', 2
    switch -CaseSensitive ($kind) {
        'family' { $title = "Drift: API gaps in the '$value' endpoint family" }
        'systemic' { $title = "Drift: parameter '$value' is missing across endpoint families" }
        'envelope' { $title = "Drift: response envelope field '$value' is not surfaced" }
        'validateset' { $title = "Drift: ValidateSet review for $value" }
        'deadkey' { $title = "Drift: dead or unreachable request keys in the '$value' family" }
        'reopen' { $title = "Drift: findings still reported after #$value was closed" }
        default { throw "Unknown drift group kind in '$GroupKey'." }
    }
    if ([string]::IsNullOrEmpty($value) -or $title -cnotmatch "^[A-Za-z0-9 _:'#.,()/-]+$") {
        throw "The title for '$GroupKey' would carry characters that are unsafe on a command line: $title"
    }
    return $title
}

function Get-PfbDriftIssueLabel {
    <#
    .SYNOPSIS
        The labels a new drift issue is created with.
    .DESCRIPTION
        source:drift, status:triage, needs:live-test, and exactly one area: label --
        docs/TRIAGE-ROLES.md makes area: single-valued, and a family group can mix
        uncovered endpoints with wire-contract gaps. The area follows the group's most
        severe finding: area:cmdlet-coverage when that is an uncovered endpoint, else
        area:wire-contract. Never a priority: label -- status:triage means unassessed.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory = $true)][object[]]$Finding)

    $items = @(Get-PfbDriftItem $Finding)
    $minimum = ($items | Measure-Object -Property Severity -Minimum).Minimum
    $area = $script:PfbDriftLabel.Wire
    if (@($items | Where-Object { $_.Severity -eq $minimum -and $_.Category -ceq 'uncoveredEndpoint' }).Count -gt 0) {
        $area = $script:PfbDriftLabel.Coverage
    }
    $script:PfbDriftLabel.Source
    $script:PfbDriftLabel.Triage
    $script:PfbDriftLabel.LiveTest
    $area
}

function Format-PfbDriftFindingDetail {
    <#
    .SYNOPSIS
        One table cell describing a finding, with pipes escaped and newlines flattened.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory = $true)]$Finding)

    $d = $Finding.Detail
    switch -CaseSensitive ($Finding.Category) {
        'uncoveredEndpoint' { $text = "no cmdlet; in the spec since REST $($d.MinVersion)" }
        'parameterGap' {
            $text = "$($d.Location) parameter; cmdlets: $(@($d.Cmdlets) -join ', ')"
            if ($d.Confidence -eq 'partial') { $text += '; confidence: partial' }
            if (@($d.Annotations).Count -gt 0) { $text += "; note: $(@($d.Annotations) -join '; ')" }
        }
        'responseFieldRemoval' { $text = "removed from the response; present REST $($d.IntroducedVersion) to $($d.LastSeenVersion)" }
        'responseFieldRename' { $text = "renamed $($d.From) -> $($d.To) at REST $($d.Version)" }
        'validateSetDrift' { $text = "-$($d.Parameter): ValidateSet $($d.Kind) value '$($d.Value)'" }
        'newValidateSetCandidate' { $text = "-$($d.Parameter) ($($d.WireName)): $($d.Recommendation); spec values: $(@($d.SpecValues) -join ', ')" }
        'unhandledEnvelopeField' { $text = "not read by Invoke-PfbApiRequest; on $($d.EndpointCount) endpoint(s)" }
        'deadKey' { $text = "$($d.ReportSeverity) / $($d.Classification); $(@($d.Parameters) -join ', ')" }
        'noSurvivingSelector' { $text = "no selector survives; cmdlets: $(@($d.Cmdlets) -join ', ')" }
        default { throw "Unknown drift category '$($Finding.Category)'." }
    }
    return (($text -replace '\|', '\|') -replace "[`r`n]+", ' ')
}

function Format-PfbDriftFindingTable {
    <#
    .SYNOPSIS
        A markdown table of findings: header, separator, one row each, most severe first.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory = $true)][object[]]$Finding)

    $tick = [string][char]0x60
    $rows = [System.Collections.Generic.List[object]]::new()
    foreach ($f in @(Get-PfbDriftItem $Finding)) { $rows.Add($f) }
    $rows.Sort([System.Comparison[object]] {
            param($a, $b)
            $c = ([int]$a.Severity).CompareTo([int]$b.Severity)
            if ($c -ne 0) { return $c }
            $c = [string]::CompareOrdinal($a.Endpoint, $b.Endpoint)
            if ($c -ne 0) { return $c }
            $c = [string]::CompareOrdinal($a.Field, $b.Field)
            if ($c -ne 0) { return $c }
            return [string]::CompareOrdinal($a.Fingerprint, $b.Fingerprint)
        })

    '| Category | Endpoint | Field | Detail | Fingerprint |'
    '|---|---|---|---|---|'
    foreach ($f in $rows) {
        $endpoint = '-'
        if ($f.Endpoint -ne '') { $endpoint = $tick + $f.Endpoint + $tick }
        $field = '-'
        if ($f.Field -ne '') { $field = $tick + $f.Field + $tick }
        '| {0} | {1} | {2} | {3} | {4} |' -f $f.Category, $endpoint, $field, (Format-PfbDriftFindingDetail -Finding $f), ($tick + $f.Fingerprint + $tick)
    }
}

function Format-PfbDriftIssueBody {
    <#
    .SYNOPSIS
        The body of a new drift issue: disclaimer, summary, findings table, maintenance
        notes, and the machine block last.
    .DESCRIPTION
        The findings table is truncated, with a note, if the body would pass
        $script:PfbDriftBodyLimit; the machine block always carries every fingerprint.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)][string]$GroupKey,
        [Parameter(Mandatory = $true)][object[]]$Finding,
        [AllowEmptyString()][string]$SourceNote = ''
    )

    $tick = [string][char]0x60
    $items = @(Get-PfbDriftItem $Finding)
    $kind, $value = $GroupKey -split ':', 2
    $families = @(Get-PfbDriftSortedString -Value @($items | ForEach-Object { $_.Family } | Where-Object { $_ -ne '' }))
    switch -CaseSensitive ($kind) {
        'family' { $summary = "Gaps between the module and the published REST spec in the $tick$value$tick endpoint family: every endpoint whose path starts $tick/$value$tick." }
        'systemic' { $summary = "The parameter $tick$value$tick is missing from cmdlets in $($families.Count) endpoint families. A parameter missing from 3 or more families is filed once, here, and kept out of the per-family issues." }
        'envelope' { $summary = "The response envelope field $tick$value$tick is not read by ${tick}Invoke-PfbApiRequest$tick, so callers never see it." }
        'validateset' { $summary = "ValidateSet findings for ${tick}$value${tick}: a declared set that disagrees with the spec, or a parameter the spec gives a fixed list of values." }
        'deadkey' { $summary = "Request keys in the $tick$value$tick family that the spec does not accept where the cmdlet sends them, and cmdlets left with no working selector. The fix is to remove or relocate, not to add." }
        'reopen' { $summary = "These findings are still reported after #$value was closed as completed: the fix was partial, or the finding came back." }
        default { throw "Unknown drift group kind in '$GroupKey'." }
    }

    $categoryNames = @(Get-PfbDriftSortedString -Value @($items | ForEach-Object { $_.Category }))
    $counts = @(foreach ($name in $categoryNames) {
            '{0} {1}' -f $name, @($items | Where-Object { $_.Category -ceq $name }).Count
        })
    $partial = @($items | Where-Object { $_.Category -ceq 'parameterGap' -and $_.Detail.Confidence -eq 'partial' }).Count
    $marker = Format-PfbDriftMarker -Marker ([PSCustomObject]@{
            Kind         = 'group'
            GroupKey     = $GroupKey
            Fingerprints = @($items | ForEach-Object { $_.Fingerprint })
            Vanished     = @()
        })

    $head = [System.Collections.Generic.List[string]]::new()
    $head.Add($script:PfbDriftDisclaimer)
    $head.Add('')
    $head.Add('## Summary')
    $head.Add('')
    $head.Add($summary)
    $head.Add('')
    $head.Add("**Findings:** $($items.Count) ($($counts -join ', '))")
    if ($SourceNote -ne '') {
        $head.Add('')
        $head.Add("**Source:** $SourceNote")
    }
    if ($partial -gt 0) {
        $head.Add('')
        $head.Add("**Partial confidence:** $partial row(s) come from endpoints the drift report marks ${tick}partial${tick}. Read 'How to read this report' in ${tick}Reports/PfbApiDriftReport.md$tick before acting on them.")
    }
    $head.Add('')
    $head.Add('## Findings')
    $head.Add('')

    $foot = @(
        ''
        '## How this issue is maintained'
        ''
        "${tick}tools/New-PfbDriftIssue.ps1$tick reconciles this issue against the committed drift reports. It rewrites only the machine block at the end of this body, and comments whenever findings are added, stop being reported, or come back. It never closes an issue."
        ''
        "- Close as **not planned** to decline these findings for good; they will not be filed again. Record the reasoning in ${tick}docs/settled/$tick."
        '- Close as **completed** when the work is done. A finding still reported after that is filed again, in a new issue that links here.'
        ''
        $marker
    )

    $nl = "`n"
    $table = @(Format-PfbDriftFindingTable -Finding $items)
    $fixedLength = ($head -join $nl).Length + ($foot -join $nl).Length + 2
    $budget = $script:PfbDriftBodyLimit - $fixedLength - 300
    if ($budget -lt ($table[0].Length + $table[1].Length + 2)) {
        throw "Group '$GroupKey' has too many findings ($($items.Count)) for one issue body even with its table omitted."
    }
    $used = 0
    $kept = 0
    foreach ($line in $table) {
        if ($used + $line.Length + 1 -gt $budget) { break }
        $used += $line.Length + 1
        $kept++
    }

    $lines = [System.Collections.Generic.List[string]]::new()
    foreach ($line in $head) { $lines.Add($line) }
    for ($i = 0; $i -lt $kept; $i++) { $lines.Add($table[$i]) }
    if ($kept -lt $table.Count) {
        $lines.Add('')
        $lines.Add("_$($table.Count - $kept) more finding(s) not listed, to stay under GitHub's body limit. Every fingerprint is in the machine block below._")
    }
    foreach ($line in $foot) { $lines.Add($line) }
    return ($lines -join $nl)
}

function Format-PfbDriftComment {
    <#
    .SYNOPSIS
        The visible comment posted whenever the reconciler changes an issue's machine block.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [AllowEmptyCollection()][object[]]$Added = @(),
        [AllowEmptyCollection()][object[]]$Reappeared = @(),
        [AllowEmptyCollection()][string[]]$Vanished = @(),
        [switch]$Resolved,
        [AllowEmptyCollection()][string[]]$ReplacedStatus = @(),
        [switch]$Unresolved
    )

    $tick = [string][char]0x60
    $added = @(Get-PfbDriftItem $Added)
    $back = @(Get-PfbDriftItem $Reappeared)
    $gone = @(Get-PfbDriftSortedString -Value @(Get-PfbDriftItem $Vanished))

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add($script:PfbDriftDisclaimer)
    if ($added.Count -gt 0) {
        $lines.Add('')
        $lines.Add("**Added ($($added.Count)):** newly reported findings in this issue's group.")
        $lines.Add('')
        foreach ($line in @(Format-PfbDriftFindingTable -Finding $added)) { $lines.Add($line) }
    }
    if ($back.Count -gt 0) {
        $lines.Add('')
        $lines.Add("**Reported again ($($back.Count)):** findings this issue had recorded as no longer reported.")
        $lines.Add('')
        foreach ($line in @(Format-PfbDriftFindingTable -Finding $back)) { $lines.Add($line) }
    }
    if ($gone.Count -gt 0) {
        $lines.Add('')
        $lines.Add("**No longer reported ($($gone.Count)):** " + (@($gone | ForEach-Object { $tick + $_ + $tick }) -join ', '))
        $lines.Add('')
        $lines.Add("They stay in the machine block as vanished, so this is said once. This issue's findings table shows what each fingerprint was.")
    }
    if ($Resolved) {
        $replaced = ''
        $statuses = @(Get-PfbDriftItem $ReplacedStatus)
        if ($statuses.Count -gt 0) {
            $replaced = ' (replacing ' + (@($statuses | ForEach-Object { $tick + $_ + $tick }) -join ', ') + ')'
        }
        $lines.Add('')
        $lines.Add("None of this issue's findings are reported any more, so it is now labelled ${tick}status:resolved-upstream$tick$replaced. A person should confirm and close it; this tool never closes issues.")
    }
    if ($Unresolved) {
        $lines.Add('')
        $lines.Add("This issue has findings that are still reported, so ${tick}status:resolved-upstream$tick was replaced with ${tick}status:triage$tick.")
    }
    if ($lines.Count -eq 1) { throw 'A drift comment needs at least one change to report.' }
    return ($lines -join "`n")
}

function ConvertFrom-PfbSettledDriftKey {
    <#
    .SYNOPSIS
        Reads the optional '**Drift keys:**' field of one docs/settled/ entry.
    .DESCRIPTION
        Keys are comma- or space-separated, backticks optional:
          fp:<16 hex>        one finding, by fingerprint
          param:<wire name>  every parameterGap finding for that wire name
          family:<segment>   every finding whose endpoint family is <segment>
          category:<token>   every finding of that category
        An unrecognised key throws, naming the file: a typo that silently matched nothing
        would re-file exactly the finding the entry declined. Lines inside a fenced code
        block are ignored, so an entry (or the README) can show an example.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$Text,
        [Parameter(Mandatory = $true)][string]$Source
    )

    $fence = $null
    foreach ($line in (($Text -replace "`r`n", "`n" -replace "`r", "`n") -split "`n")) {
        $trimmed = $line.Trim()
        $wasInFence = $null -ne $fence
        $fence = Get-PfbDriftFenceState -Line $line -State $fence
        if ($wasInFence -or ($null -ne $fence)) { continue }
        if (-not ($trimmed -match '^\*\*Drift keys:\*\*(?<rest>.*)$')) { continue }
        $rest = $Matches['rest']
        foreach ($token in ($rest -split '[,\s]+')) {
            $clean = $token.Trim().Trim([char]0x60)
            if ($clean -eq '') { continue }
            if (-not ($clean -cmatch '^(?<kind>fp|param|family|category):(?<value>\S+)$')) {
                throw "$Source has an unrecognised drift key '$clean'. Keys are fp:, param:, family: or category: (docs/settled/README.md). The reconciler stops rather than ignore it, because an ignored key would re-file the finding this entry declined."
            }
            $kind = $Matches['kind']
            $value = $Matches['value']
            if ($kind -ceq 'fp' -and $value -cnotmatch '^[0-9a-f]{16}$') {
                throw "$Source has drift key '$clean', but a fingerprint is 16 lowercase hex characters."
            }
            if ($kind -ceq 'category' -and $script:PfbDriftCategoryToken -cnotcontains $value) {
                throw "$Source has drift key '$clean', but '$value' is not a category token ($($script:PfbDriftCategoryToken -join ', '))."
            }
            [PSCustomObject]@{ Kind = $kind; Value = $value; Raw = $clean; Source = $Source }
        }
    }
}

function Find-PfbSettledDriftKey {
    <#
    .SYNOPSIS
        The first settled key that matches a finding, or $null.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]$Finding,
        [AllowEmptyCollection()][object[]]$SettledKey = @()
    )

    foreach ($key in @(Get-PfbDriftItem $SettledKey)) {
        $hit = $false
        switch -CaseSensitive ($key.Kind) {
            'fp' { $hit = $Finding.Fingerprint -ceq $key.Value }
            'param' { $hit = ($Finding.Category -ceq 'parameterGap') -and ($Finding.Parameter -ceq $key.Value) }
            'family' { $hit = $Finding.Family -ceq $key.Value }
            'category' { $hit = $Finding.Category -ceq $key.Value }
        }
        if ($hit) { return $key }
    }
    return $null
}

function Get-PfbDriftFindingDisposition {
    <#
    .SYNOPSIS
        Decides, per finding, which row of the reconcile table applies.
    .DESCRIPTION
        First match wins:
          Tracked     an OPEN issue records the fingerprint                    -> nothing
          Reappeared  an OPEN issue records it as vanished                     -> move it back
          Settled     a docs/settled/ Drift key matches                        -> skip
          Declined    a CLOSED not-planned issue records it                    -> skip, 'declined #N'
          Create/     a CLOSED completed issue records it (a close with no     -> group reopen:<N>;
            Append      recorded reason counts as completed; N = the newest)     append if open, else create
          Append      the finding's group has an OPEN group issue              -> append
          Create      none of the above                                        -> queue for creation
        Open issues come first because an open issue is the current claim on a finding,
        and because it is what makes a "still reported after #N" issue idempotent: once
        filed, the next run finds the fingerprint open and leaves it. A CLOSED duplicate is
        ignored -- the issue it duplicates carries the decision. A closed issue's vanished
        list counts with its fingerprints: it was that issue's finding either way. Where
        several issues qualify, the lowest-numbered open issue wins; for a completed
        close, the highest number (the most recent) names the reopen group.

        Only an issue with a Marker counts, and ConvertFrom-PfbDriftIssue sets one only on
        an issue labelled source:drift: a block on anyone else's issue claims nothing.
    .OUTPUTS
        [PSCustomObject] Finding, Disposition, GroupKey, IssueNumber, ReopenedFrom, Reason.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][AllowEmptyCollection()][object[]]$Finding,
        [Parameter(Mandatory = $true)][AllowEmptyCollection()][object[]]$Issue,
        [AllowEmptyCollection()][object[]]$SettledKey = @()
    )

    $activeOpen = @{}
    $vanishedOpen = @{}
    $declined = @{}
    $completed = @{}
    $openGroup = [System.Collections.Generic.Dictionary[string, int]]::new([System.StringComparer]::Ordinal)

    $issues = @(@(Get-PfbDriftItem $Issue) | Where-Object { $null -ne $_.Marker } | Sort-Object -Property Number)
    foreach ($item in $issues) {
        $marker = $item.Marker
        if ($item.State -ceq 'OPEN') {
            foreach ($fp in @(Get-PfbDriftItem $marker.Fingerprints)) {
                if (-not $activeOpen.ContainsKey($fp)) { $activeOpen[$fp] = $item.Number }
            }
            foreach ($fp in @(Get-PfbDriftItem $marker.Vanished)) {
                if (-not $vanishedOpen.ContainsKey($fp)) { $vanishedOpen[$fp] = $item.Number }
            }
            if ($marker.Kind -ceq 'group' -and -not $openGroup.ContainsKey($marker.GroupKey)) {
                $openGroup[$marker.GroupKey] = $item.Number
            }
            continue
        }
        $all = @(Get-PfbDriftItem $marker.Fingerprints) + @(Get-PfbDriftItem $marker.Vanished)
        switch -CaseSensitive ($item.StateReason) {
            'NOT_PLANNED' {
                foreach ($fp in $all) { if (-not $declined.ContainsKey($fp)) { $declined[$fp] = $item.Number } }
            }
            'DUPLICATE' { }
            default {
                foreach ($fp in $all) { $completed[$fp] = $item.Number }
            }
        }
    }

    foreach ($f in @(Get-PfbDriftItem $Finding)) {
        $fp = $f.Fingerprint
        $disposition = 'Create'
        $groupKey = $f.GroupKey
        $number = $null
        $reopenedFrom = 0
        $reason = 'new'

        $key = $null
        if (-not $activeOpen.ContainsKey($fp) -and -not $vanishedOpen.ContainsKey($fp)) {
            $key = Find-PfbSettledDriftKey -Finding $f -SettledKey $SettledKey
        }

        if ($activeOpen.ContainsKey($fp)) {
            $disposition = 'Tracked'
            $number = $activeOpen[$fp]
            $reason = "tracked in #$number"
        }
        elseif ($vanishedOpen.ContainsKey($fp)) {
            $disposition = 'Reappeared'
            $number = $vanishedOpen[$fp]
            $reason = "reported again; #$number recorded it as vanished"
        }
        elseif ($null -ne $key) {
            $disposition = 'Settled'
            $reason = "settled: $($key.Source) ($($key.Raw))"
        }
        elseif ($declined.ContainsKey($fp)) {
            $disposition = 'Declined'
            $number = $declined[$fp]
            $reason = "declined #$number"
        }
        elseif ($completed.ContainsKey($fp)) {
            $reopenedFrom = $completed[$fp]
            $groupKey = "reopen:$reopenedFrom"
            $reason = "still reported after #$reopenedFrom closed"
            if ($openGroup.ContainsKey($groupKey)) {
                $disposition = 'Append'
                $number = $openGroup[$groupKey]
                $reason += "; append to #$number"
            }
        }
        elseif ($openGroup.ContainsKey($groupKey)) {
            $disposition = 'Append'
            $number = $openGroup[$groupKey]
            $reason = "append to #$number"
        }

        [PSCustomObject]@{
            Finding      = $f
            Disposition  = $disposition
            GroupKey     = $groupKey
            IssueNumber  = $number
            ReopenedFrom = $reopenedFrom
            Reason       = $reason
        }
    }
}
