#Requires -Version 5.1
<#
.SYNOPSIS
    The pure half of the drift -> GitHub issue reconciler (tools/New-PfbDriftIssue.ps1).
.DESCRIPTION
    Turns Reports/PfbApiDriftReport.json and Reports/PfbDeadKeyReport.json into one
    fingerprinted finding per atomic gap, groups the findings into issue-sized units, and
    plans the issue writes that reconcile them with what GitHub already holds.

    Nothing here touches the network or the filesystem. The shell script owns every read
    and write, so each rule below is testable against in-memory fixtures
    (Tests/PfbDriftIssueTools.Tests.ps1) with no token and no repository.

    THE FINGERPRINT IS A PUBLIC, PERMANENT KEY. It is stamped into issue bodies on
    github.com, closed issues included, and GitHub issues are the reconciler's only state --
    there is no baseline file. Changing the tuple, a category token, the separator or the
    hash re-keys every stamped issue at once: every open issue's findings "vanish" (the
    restructure guard then aborts every run) and every declined finding becomes eligible to
    be filed again. Treat $script:PfbDriftCategoryToken and Get-PfbDriftFingerprint as
    frozen; the golden values in the test file exist to make an accidental change red.

    5.1-compatible for the same reason as tools/lib/PfbAgentBriefTools.ps1: nothing here
    needs 7, and claiming 7 would make the test file skip on the winps51 leg, which the
    coverage gate would then require to be pinned in Tests/coverage-baseline.psd1.
    Pure ASCII on purpose: PSUseBOMForUnicodeEncodedFile is held at zero repo-wide.
#>

# Category tokens. PART OF THE FINGERPRINT -- see the note above before touching one.
$script:PfbDriftCategoryToken = @(
    'deadKey'
    'noSurvivingSelector'
    'responseFieldRemoval'
    'responseFieldRename'
    'validateSetDrift'
    'uncoveredEndpoint'
    'unhandledEnvelopeField'
    'parameterGap'
    'newValidateSetCandidate'
)

# Lower is more severe. Orders creation under -MaxCreate and picks the area: label.
# Correctness defects first (a dead key sends something the array ignores; a removed or
# renamed response field breaks callers; a stale ValidateSet rejects legal values), then
# missing surface (an uncovered endpoint, an unread envelope field, a missing parameter),
# then an ergonomic suggestion last.
$script:PfbDriftSeverity = @{
    deadKey                 = 1
    noSurvivingSelector     = 1
    responseFieldRemoval    = 2
    responseFieldRename     = 3
    validateSetDrift        = 4
    uncoveredEndpoint       = 5
    unhandledEnvelopeField  = 6
    parameterGap            = 7
    newValidateSetCandidate = 8
}

$script:PfbDriftSystemicFamilyThreshold = 3
$script:PfbDriftVanishThreshold = 0.25

# GitHub rejects an issue body over 65,536 characters; this leaves headroom.
$script:PfbDriftBodyLimit = 60000

$script:PfbDriftGroupKeyPattern = '^(family|systemic|envelope|validateset|deadkey|reopen):[A-Za-z0-9_.-]+$'

# Built from its code point so no line of this file begins with a literal fence.
$script:PfbDriftFence = ([string][char]0x60) * 3

$script:PfbDriftDisclaimer = '> *Generated by automation: `tools/New-PfbDriftIssue.ps1`, reconciling the committed drift reports. No person reviewed this text before it was posted.*'

$script:PfbDriftLabel = @{
    Source   = 'source:drift'
    Triage   = 'status:triage'
    LiveTest = 'needs:live-test'
    Coverage = 'area:cmdlet-coverage'
    Wire     = 'area:wire-contract'
    Resolved = 'status:resolved-upstream'
}

$script:PfbDriftReportRequiredProperty = @(
    'schemaVersion'
    'uncoveredEndpoints'
    'parameterGaps'
    'validateSetDrift'
    'newValidateSetCandidates'
    'responseFieldRemovals'
    'responseFieldRenameCandidates'
    'unhandledResponseEnvelopeFields'
)
$script:PfbDeadKeyReportRequiredProperty = @('deadKeys', 'noSurvivingSelector')

function Get-PfbDriftItem {
    <#
    .SYNOPSIS
        The non-null elements of a report or issue collection.
    .DESCRIPTION
        @($x) on a JSON null is a ONE-element array holding $null, so iterating a property
        that is null rather than [] would hand every loop body a $null row. Wrap every
        collection read from a report or from gh in this before iterating it, and wrap the
        call in @().
    #>
    [CmdletBinding()]
    param([Parameter(Position = 0)][AllowNull()]$Value)

    foreach ($item in @($Value)) {
        if ($null -ne $item) { $item }
    }
}

function Get-PfbDriftSortedString {
    <#
    .SYNOPSIS
        Ordinal, de-duplicated sort of a string list.
    .DESCRIPTION
        Sort-Object is culture-aware, and the two editions this repo gates on disagree on
        invariant linguistic order (5.1 ignores hyphens when collating; 7 does not). A
        fingerprint list sorted with it would reorder between editions and every machine
        block would churn. Ordinal comparison is identical on both. Same reasoning as
        Sort-PfbSelectorString in tools/lib/PfbPipelineSelectorTools.ps1, which cannot be
        reused: that file is PowerShell 7 only and its verb is unapproved.
    .OUTPUTS
        [string] -- one element at a time; wrap the call in @().
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Position = 0)][AllowNull()][AllowEmptyCollection()][string[]]$Value)

    $set = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    foreach ($item in @($Value)) {
        if ($null -ne $item) { [void]$set.Add($item) }
    }
    $list = [System.Collections.Generic.List[string]]::new($set)
    $list.Sort([System.StringComparer]::Ordinal)
    foreach ($item in $list) { $item }
}

function ConvertTo-PfbDriftEndpoint {
    <#
    .SYNOPSIS
        Normalises an endpoint to the 'METHOD /path' form fingerprints are computed over.
    .DESCRIPTION
        The drift report writes 'GET /alerts'; the dead-key report writes method 'GET' and
        endpoint 'alerts' separately, with no leading slash. Both must produce one string,
        or the same gap would carry two fingerprints depending on which report found it.
    #>
    [CmdletBinding(DefaultParameterSetName = 'Key')]
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true, ParameterSetName = 'Key')][string]$Endpoint,
        [Parameter(Mandatory = $true, ParameterSetName = 'Parts')][string]$Method,
        [Parameter(Mandatory = $true, ParameterSetName = 'Parts')][string]$Path
    )

    if ($PSCmdlet.ParameterSetName -eq 'Key') {
        $parts = $Endpoint.Trim() -split '\s+', 2
        if ($parts.Count -ne 2) { throw "Endpoint '$Endpoint' is not in 'METHOD /path' form." }
        $Method = $parts[0]
        $Path = $parts[1]
    }

    $verb = $Method.Trim().ToUpperInvariant()
    if ($verb -cnotmatch '^[A-Z]+$') { throw "'$Method' is not an HTTP method." }
    $trimmed = $Path.Trim().Trim('/')
    if ($trimmed -eq '' -or $trimmed -match '\s' -or $trimmed.Contains('|')) {
        throw "Path '$Path' cannot be normalised into an endpoint."
    }
    return ('{0} /{1}' -f $verb, $trimmed)
}

function Get-PfbDriftFamily {
    <#
    .SYNOPSIS
        The endpoint family: the first path segment of a 'METHOD /path' endpoint.
    .DESCRIPTION
        Matches Get-PfbSelectorProducerIndex in tools/lib/PfbPipelineSelectorTools.ps1:
        split on the first space, trim the leading slash, take the first '/' segment.
        Re-implemented rather than shared because that file is PowerShell 7 only.
        'GET /api/login-banner' is family 'api'. A finding with no endpoint has family ''.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory = $true)][AllowEmptyString()][string]$Endpoint)

    if ($Endpoint -eq '') { return '' }
    $parts = $Endpoint -split ' ', 2
    if ($parts.Count -ne 2) { throw "Endpoint '$Endpoint' is not in 'METHOD /path' form." }
    return (($parts[1].TrimStart('/')) -split '/')[0]
}

function Get-PfbDriftFingerprint {
    <#
    .SYNOPSIS
        sha256('<category>|<METHOD /path>|<field>'), first 16 lowercase hex characters.
    .DESCRIPTION
        No version component, so a finding keeps its fingerprint across spec releases. The
        per-category tuple is documented in tools/README.md; an absent component is the
        empty string, never omitted, so 'uncoveredEndpoint|GET /x|' keeps both separators.
        FROZEN -- see the note at the top of this file.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)][string]$Category,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$Endpoint,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$Field
    )

    if ($script:PfbDriftCategoryToken -cnotcontains $Category) {
        throw "'$Category' is not a drift category token ($($script:PfbDriftCategoryToken -join ', '))."
    }
    if ($Endpoint.Contains('|') -or $Field.Contains('|')) {
        throw "'|' is the fingerprint separator and cannot appear in an endpoint or field ('$Endpoint', '$Field')."
    }

    $text = '{0}|{1}|{2}' -f $Category, $Endpoint, $Field
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = $sha.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($text))
    }
    finally {
        $sha.Dispose()
    }
    $hex = -join ($bytes | ForEach-Object { $_.ToString('x2') })
    return $hex.Substring(0, 16)
}
