function New-PfbFleetMember {
    <#
    .SYNOPSIS
        Adds a member to a fleet on a FlashBlade array.
    .DESCRIPTION
        The New-PfbFleetMember cmdlet adds an array as a member of a fleet on the connected
        Pure Storage FlashBlade. Per the FlashBlade REST API spec, `POST /fleets/members` must
        be called from the array that is joining the fleet, and it identifies the fleet via a
        `fleet_ids`/`fleet_names` query parameter plus a request body carrying the fleet key
        (generated on any array already in the fleet) and a reference to the joining array
        itself.

        CONFIRMED WIRE-CONTRACT BUG (issue #38): this cmdlet previously sent `fleet_names` and
        `member_names` as bare query parameters with no request body at all. `member_names` is
        not a valid query parameter for this endpoint (only `fleet_ids`/`fleet_names` are, per
        the OpenAPI spec's parameter list for POST /fleets/members) and there was no way to
        supply the required fleet key or self-identification, so this cmdlet could never have
        succeeded against a real array. -MemberName has been removed; -Members now exposes the
        actual request body so a caller can supply the correct shape, e.g.:
        `-Members @{ key = $fleetKey; member = @{ id = $thisArrayId } }`.

        The fix is verified against the OpenAPI spec (FleetMemberPost schema and the POST
        operation's parameter list) but has NOT been live-tested against a real fleet -- that
        happens in a later task against a lab array. See docs in issue #38's
        issue38-fleetmember-bug-comment.md for the full context.
    .PARAMETER FleetName
        The fleet name to add the member to. Sent as the `fleet_names` query parameter.
    .PARAMETER FleetId
        The fleet ID to add the member to. Sent as the `fleet_ids` query parameter.
    .PARAMETER Members
        Info about the members being added to the fleet, as a hashtable or array of hashtables
        -- for example @{ key = "<fleet key>"; member = @{ id = "<this array's own id>" } }.
        The `key` is the fleet key generated on any array already in the fleet; `member` is a
        reference to the array joining the fleet.
    .PARAMETER Array
        The FlashBlade connection object. If not specified, the default connection is used.
    .EXAMPLE
        New-PfbFleetMember -FleetName "fleet-prod" -Members @{ key = "1fc6297a-5183-4b7a-8d58-0182af1a2b64"; member = @{ id = "10314f42-020d-7080-8013-000ddt400012" } }

        Adds this array to "fleet-prod" using the fleet key generated by an existing fleet member.
    .EXAMPLE
        New-PfbFleetMember -FleetId "10314f42-020d-7080-8013-000ddt400099" -Members @{ key = "key-456"; member = @{ id = "this-array-id" } } -WhatIf

        Shows what would happen without actually adding the member, identifying the fleet by ID.
    #>
    [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'Medium')]
    param(
        [Parameter()] [string]$FleetName,
        [Parameter()] [string]$FleetId,
        [Parameter()] [hashtable[]]$Members,
        [Parameter()] [PSCustomObject]$Array
    )

    Assert-PfbConnection -Array ([ref]$Array)

    $queryParams = @{}
    if ($PSBoundParameters.ContainsKey('FleetName')) { $queryParams['fleet_names'] = $FleetName }
    if ($PSBoundParameters.ContainsKey('FleetId'))   { $queryParams['fleet_ids']   = $FleetId }

    # Constraint 8(c): each members[] item is {key, member}, where `key` is a plain string
    # outside {id, name, resource_type} -- this makes the array COMPOSITE, not an array of
    # references, so it is passed straight through rather than projected into @{ name = ... }.
    $body = @{}
    if ($PSBoundParameters.ContainsKey('Members')) { $body['members'] = @($Members) }

    $target = if ($FleetName) { $FleetName } elseif ($FleetId) { $FleetId } else { 'fleet member' }

    if ($PSCmdlet.ShouldProcess($target, 'Add fleet member')) {
        Invoke-PfbApiRequest -Array $Array -Method POST -Endpoint 'fleets/members' -Body $body -QueryParams $queryParams
    }
}
