#Requires -Version 7.0
<#
.SYNOPSIS
    Fails the build when a committed Data/ or Reports/ artifact does not match what its
    generator produces from the same inputs.
.DESCRIPTION
    Data/ and Reports/ hold eleven artifacts generated by tools/Build-*.ps1. Nothing
    regenerated them on a pull request: update-api-capability-map.yml rebuilds them, but only
    on schedule, on push to main, and on workflow_dispatch. A PR that changed a generator, or
    added a Public/ cmdlet the generators read, therefore landed with stale committed
    artifacts and a green CI run -- the same drift then had to be found by hand twice
    (issues #96, #97).

    THE LOAD-BEARING DECISION -- the spec set is pinned, not discovered. Every generator reads
    tools/specs/. If this gate simply used whatever specs the cache holds, a newly published
    REST version would change the drift report and red an unrelated PR; that is exactly why
    the pre-existing check in update-api-capability-map.yml was left advisory. So the pinned
    set is Data/PfbCapabilityMap.json's own `generatedFrom` list, and staging copies that
    explicit list of files rather than the directory -- a stray fb2.29.json cannot leak in.
    That separates PR-caused drift from spec-publication drift, which is what makes this
    safe to make blocking.

    COMPARISON NORMALIZES LINE ENDINGS. The repo has no .gitattributes and Windows checkouts
    run core.autocrlf=true, so Reports/PfbApiDriftReport.md is CRLF in a Windows working tree
    while the generators (and Linux CI) emit LF. A raw byte comparison would fail every local
    run while passing in CI -- a gate that is wrong in the direction that trains people to
    ignore it.

    THE WORKING TREE IS NEVER TOUCHED. Regeneration goes to a scratch directory; a gate that
    rewrites Data/ as a side effect of checking it is not a gate.

    Lives in scripts/ rather than tools/ because the workflows call scripts/ (see
    scripts/Publish-Gallery.ps1, scripts/Invoke-PfbCiPester.ps1) and because a developer must
    be able to answer the same question locally before pushing.

    Data/PfbVersionMap.json is deliberately NOT covered: Update-PfbVersionMap.ps1 needs the
    SSOT_API_KEY secret, which is absent on fork PRs, so including it would fail for want of
    a credential rather than for staleness.
.PARAMETER SpecsDirectory
    Source of the OpenAPI spec cache. Defaults to tools/specs relative to the repo root.
    Only the pinned versions are read from it.
.PARAMETER WorkDirectory
    Scratch root for the staged specs and the regenerated output. Defaults to a new directory
    under the system temp path. Created if absent.
.PARAMETER Artifact
    Optional subset of repo-relative artifact paths to check; defaults to all eleven. A full
    regeneration takes minutes, so a developer who touched one generator wants one check --
    only the generators needed to produce the requested artifacts (and their upstream inputs)
    are run.
.PARAMETER KeepWorkDirectory
    Leave the scratch tree in place and print its path, so a reported difference can be
    diffed by hand instead of being re-derived.
.EXAMPLE
    ./scripts/Assert-PfbDerivedArtifacts.ps1
.EXAMPLE
    ./scripts/Assert-PfbDerivedArtifacts.ps1 -Artifact Data/PfbCapabilityMap.json -KeepWorkDirectory
#>
[CmdletBinding()]
param(
    [string]$SpecsDirectory,
    [string]$WorkDirectory,
    [string[]]$Artifact,
    [switch]$KeepWorkDirectory
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$toolsDir = Join-Path $repoRoot 'tools'

if (-not $SpecsDirectory) { $SpecsDirectory = Join-Path $repoRoot 'tools/specs' }

# The generation graph, in dependency order. `Step` groups artifacts by the single generator
# invocation that emits them (three generators emit a .json/.md pair), and `DependsOn` names
# the steps whose REGENERATED output this step must read. Downstream generators reading the
# COMMITTED upstream artifact would be a false pass on the exact case this gate exists for: a
# PR changing Build-PfbCapabilityMap.ps1 would produce a new capability map but a drift report
# built from the stale committed one.
$script:ArtifactPlan = @(
    [pscustomobject]@{ Step = 'CapabilityMap';      Generator = 'Build-PfbCapabilityMap.ps1';      DependsOn = @();                                              Artifacts = @('Data/PfbCapabilityMap.json') }
    [pscustomobject]@{ Step = 'ResponseShapeMap';   Generator = 'Build-PfbResponseShapeMap.ps1';   DependsOn = @();                                              Artifacts = @('Data/PfbResponseShapeMap.json') }
    [pscustomobject]@{ Step = 'ValueEnumMap';       Generator = 'Build-PfbValueEnumMap.ps1';       DependsOn = @();                                              Artifacts = @('Reports/PfbValueEnumMap.json', 'Reports/PfbValueEnumReconciliation.md') }
    [pscustomobject]@{ Step = 'FieldCmdletMap';     Generator = 'Build-PfbFieldCmdletMap.ps1';     DependsOn = @();                                              Artifacts = @('Reports/PfbFieldCmdletMap.json', 'Reports/PfbFieldCmdletMapping.md') }
    [pscustomobject]@{ Step = 'PipelineSelectorMap';Generator = 'Build-PfbPipelineSelectorMap.ps1';DependsOn = @('ResponseShapeMap');                            Artifacts = @('Reports/PfbPipelineSelectorMap.json', 'Reports/PfbPipelineSelectorMap.md') }
    [pscustomobject]@{ Step = 'ApiDriftReport';     Generator = 'Build-PfbApiDriftReport.ps1';     DependsOn = @('CapabilityMap', 'ResponseShapeMap', 'FieldCmdletMap'); Artifacts = @('Reports/PfbApiDriftReport.json', 'Reports/PfbApiDriftReport.md') }
    [pscustomobject]@{ Step = 'DeadKeyReport';      Generator = 'Build-PfbDeadKeyReport.ps1';      DependsOn = @('CapabilityMap');                               Artifacts = @('Reports/PfbDeadKeyReport.json') }
)

$script:AllArtifacts = @($script:ArtifactPlan | ForEach-Object { $_.Artifacts })

function ConvertTo-PfbRepoRelativePath {
    # Accepts either slash so a caller can paste a path straight out of Windows tab-completion
    # and still match the canonical forward-slash keys in $ArtifactPlan.
    param([string]$Path)
    return ($Path -replace '\\', '/') -replace '^\./', ''
}

function Get-PfbNormalizedContentHash {
    <#
        SHA256 over the UTF8 bytes of the CRLF-normalized text, not Get-FileHash over the raw
        file. See the line-endings note in the description: byte comparison red-lights every
        Windows working tree.
    #>
    param([string]$Path)

    $text = Get-Content -LiteralPath $Path -Raw
    # -Raw yields $null, not '', for a zero-byte file; .Replace() on $null would throw.
    if ($null -eq $text) { $text = '' }
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text.Replace("`r`n", "`n"))

    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
        return [System.BitConverter]::ToString($sha256.ComputeHash($bytes)).Replace('-', '')
    } finally {
        $sha256.Dispose()
    }
}

# --- Resolve the requested artifact set -------------------------------------------------

if ($Artifact) {
    $requested = @($Artifact | ForEach-Object { ConvertTo-PfbRepoRelativePath $_ })
    $unknown = @($requested | Where-Object { $script:AllArtifacts -notcontains $_ })
    if ($unknown.Count -gt 0) {
        throw "Unknown artifact(s): $($unknown -join ', '). Valid values are: $($script:AllArtifacts -join ', ')."
    }
} else {
    $requested = $script:AllArtifacts
}

# Transitive closure over DependsOn: checking only the drift report still needs a regenerated
# capability map, shape map and field-cmdlet map to feed it.
$requiredSteps = [System.Collections.Generic.HashSet[string]]::new()
foreach ($entry in $script:ArtifactPlan) {
    if (@($entry.Artifacts | Where-Object { $requested -contains $_ }).Count -gt 0) {
        [void]$requiredSteps.Add($entry.Step)
    }
}
# $ArtifactPlan is in dependency order -- a step only ever depends on an earlier one -- so a
# single back-to-front pass closes the graph without needing a fixpoint loop.
for ($i = $script:ArtifactPlan.Count - 1; $i -ge 0; $i--) {
    $entry = $script:ArtifactPlan[$i]
    if ($requiredSteps.Contains($entry.Step)) {
        foreach ($dep in $entry.DependsOn) { [void]$requiredSteps.Add($dep) }
    }
}

# --- Pin the spec set -------------------------------------------------------------------

$committedCapabilityMapPath = Join-Path $repoRoot 'Data/PfbCapabilityMap.json'
if (-not (Test-Path -LiteralPath $committedCapabilityMapPath)) {
    throw "Cannot pin the spec set: '$committedCapabilityMapPath' is missing. It carries the generatedFrom version list this gate regenerates from."
}

$pinnedVersions = @((Get-Content -LiteralPath $committedCapabilityMapPath -Raw | ConvertFrom-Json -Depth 20).generatedFrom)
if ($pinnedVersions.Count -eq 0) {
    throw "Data/PfbCapabilityMap.json has an empty or missing 'generatedFrom' list. Without it the spec set cannot be pinned, and an unpinned run is not a verification -- a newly published REST version would show up as artifact drift."
}

# --- Stage into scratch -----------------------------------------------------------------

$createdWorkDirectory = $false
if (-not $WorkDirectory) {
    $WorkDirectory = Join-Path ([System.IO.Path]::GetTempPath()) "PfbDerivedArtifacts-$([guid]::NewGuid().ToString('n'))"
}
if (-not (Test-Path -LiteralPath $WorkDirectory)) {
    New-Item -ItemType Directory -Path $WorkDirectory -Force | Out-Null
    $createdWorkDirectory = $true
}

$stagedSpecsDir = Join-Path $WorkDirectory 'specs'
$outRoot        = Join-Path $WorkDirectory 'out'
$outData        = Join-Path $outRoot 'Data'
$outReports     = Join-Path $outRoot 'Reports'

try {
    foreach ($dir in @($stagedSpecsDir, $outData, $outReports)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }

    $missingSpecs = [System.Collections.Generic.List[string]]::new()
    foreach ($version in $pinnedVersions) {
        $specName = "fb$version.json"
        $source = Join-Path $SpecsDirectory $specName
        if (-not (Test-Path -LiteralPath $source)) {
            $missingSpecs.Add($version)
            continue
        }
        Copy-Item -LiteralPath $source -Destination (Join-Path $stagedSpecsDir $specName) -Force
    }
    if ($missingSpecs.Count -gt 0) {
        # Not a warning: a partial spec set produces a thinner capability map, which this gate
        # would then report as artifact drift. Failing here names the real cause.
        throw "Spec cache '$SpecsDirectory' is missing $($missingSpecs.Count) of the $($pinnedVersions.Count) pinned REST version(s): $($missingSpecs -join ', '). Run ./tools/Update-PfbApiSpecs.ps1 to populate it. Regenerating from a partial spec set would report false drift rather than fail."
    }

    Write-Host "Pinned to $($pinnedVersions.Count) REST spec version(s) from Data/PfbCapabilityMap.json generatedFrom ($($pinnedVersions[0])..$($pinnedVersions[-1]))."
    Write-Host "Regenerating $($requiredSteps.Count) generator step(s) into $outRoot ..."

    # --- Regenerate -----------------------------------------------------------------------

    # Every downstream input below points into $outRoot, never into the repo, so each step
    # consumes what the step before it just produced. Public/ and Private/ are read from the
    # real tree on purpose -- they are the SOURCE being checked, not a derived artifact, and
    # the generators emit paths relative to them.
    $regeneratedCapabilityMap  = Join-Path $outData 'PfbCapabilityMap.json'
    $regeneratedShapeMap       = Join-Path $outData 'PfbResponseShapeMap.json'
    $regeneratedFieldCmdletMap = Join-Path $outReports 'PfbFieldCmdletMap.json'

    $stepArguments = @{
        'CapabilityMap' = @{
            SpecsDirectory = $stagedSpecsDir
            OutputPath     = $regeneratedCapabilityMap
        }
        'ResponseShapeMap' = @{
            SpecsDirectory = $stagedSpecsDir
            OutputPath     = $regeneratedShapeMap
        }
        'ValueEnumMap' = @{
            SpecsDirectory     = $stagedSpecsDir
            OutputPath         = Join-Path $outReports 'PfbValueEnumMap.json'
            ReconciliationPath = Join-Path $outReports 'PfbValueEnumReconciliation.md'
        }
        'FieldCmdletMap' = @{
            SpecsDirectory  = $stagedSpecsDir
            PublicDirectory = Join-Path $repoRoot 'Public'
            OutputPath      = $regeneratedFieldCmdletMap
            ReportPath      = Join-Path $outReports 'PfbFieldCmdletMapping.md'
        }
        'PipelineSelectorMap' = @{
            SpecsDirectory       = $stagedSpecsDir
            # The .md companion is derived from OutputPath by extension swap, so it lands in
            # $outReports automatically.
            OutputPath           = Join-Path $outReports 'PfbPipelineSelectorMap.json'
            ResponseShapeMapPath = $regeneratedShapeMap
        }
        'ApiDriftReport' = @{
            SpecsDirectory       = $stagedSpecsDir
            PublicDirectory      = Join-Path $repoRoot 'Public'
            PrivateDirectory     = Join-Path $repoRoot 'Private'
            CapabilityMapPath    = $regeneratedCapabilityMap
            FieldCmdletMapPath   = $regeneratedFieldCmdletMap
            ResponseShapeMapPath = $regeneratedShapeMap
            OutputPath           = Join-Path $outReports 'PfbApiDriftReport.json'
            ReportPath           = Join-Path $outReports 'PfbApiDriftReport.md'
        }
        'DeadKeyReport' = @{
            SpecsDirectory    = $stagedSpecsDir
            PublicDirectory   = Join-Path $repoRoot 'Public'
            CapabilityMapPath = $regeneratedCapabilityMap
            OutputPath        = Join-Path $outReports 'PfbDeadKeyReport.json'
        }
    }

    foreach ($entry in $script:ArtifactPlan) {
        if (-not $requiredSteps.Contains($entry.Step)) { continue }

        $generatorPath = Join-Path $toolsDir $entry.Generator
        if (-not (Test-Path -LiteralPath $generatorPath)) {
            throw "Generator '$generatorPath' not found; cannot verify $($entry.Artifacts -join ', ')."
        }

        Write-Host "  $($entry.Generator) -> $($entry.Artifacts -join ', ')"
        $generatorArguments = $stepArguments[$entry.Step]
        try {
            & $generatorPath @generatorArguments | Out-Null
        } catch {
            # A bare stack trace from six calls deep is unactionable in a CI log, so name the
            # generator and the artifacts it was producing before rethrowing.
            throw "Generator '$($entry.Generator)' failed while regenerating $($entry.Artifacts -join ', ') for verification: $($_.Exception.Message)"
        }
    }

    # --- Compare --------------------------------------------------------------------------

    $results = [System.Collections.Generic.List[object]]::new()
    foreach ($relative in $script:AllArtifacts) {
        if ($requested -notcontains $relative) { continue }

        $committedPath   = Join-Path $repoRoot $relative
        $regeneratedPath = Join-Path $outRoot $relative

        if (-not (Test-Path -LiteralPath $committedPath)) {
            $results.Add([pscustomobject]@{ Artifact = $relative; State = 'STALE'; Detail = 'committed copy is missing' })
            continue
        }
        if (-not (Test-Path -LiteralPath $regeneratedPath)) {
            throw "Regeneration produced no '$relative' at '$regeneratedPath'. Its generator ran without error but did not emit the file -- the artifact table in this script is out of step with the generator."
        }

        $state = 'up to date'
        $detail = ''
        if ((Get-PfbNormalizedContentHash $committedPath) -ne (Get-PfbNormalizedContentHash $regeneratedPath)) {
            $state = 'STALE'
            $detail = 'content differs from a fresh regeneration'
        }
        $results.Add([pscustomobject]@{ Artifact = $relative; State = $state; Detail = $detail })
    }

    # --- Report ---------------------------------------------------------------------------

    foreach ($result in $results) {
        $suffix = ''
        if ($result.Detail) { $suffix = " ($($result.Detail))" }
        Write-Host "$($result.Artifact): $($result.State)$suffix"
    }

    $stale = @($results | Where-Object { $_.State -eq 'STALE' })

    if ($env:GITHUB_STEP_SUMMARY) {
        $rows = foreach ($result in $results) { "| ``$($result.Artifact)`` | $($result.State) |" }
        $heading = '### Derived artifact check'
        if ($stale.Count -gt 0) { $heading = "$heading -- $($stale.Count) stale" }
        $lines = @($heading, '', "Pinned to REST $($pinnedVersions[0])-$($pinnedVersions[-1]) via ``Data/PfbCapabilityMap.json`` ``generatedFrom``.", '', '| Artifact | Result |', '|---|---|') + @($rows)
        ($lines -join [Environment]::NewLine) | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
    }
    if ($env:GITHUB_OUTPUT) {
        "stale_count=$($stale.Count)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    }

    if ($stale.Count -gt 0) {
        # Name the generators rather than a generic "rerun the build": which ones to run, and
        # in what order, is the whole question a reader has at this point.
        $staleNames = @($stale | ForEach-Object { $_.Artifact })
        $fixSteps = @(
            $script:ArtifactPlan |
                Where-Object { @($_.Artifacts | Where-Object { $staleNames -contains $_ }).Count -gt 0 } |
                ForEach-Object { "./tools/$($_.Generator)" }
        )
        throw @"
$($stale.Count) committed artifact(s) do not match a fresh regeneration: $($staleNames -join ', ').
Regenerate and commit them by running, from the repo root and in this order:
    $($fixSteps -join "`n    ")
Then commit the resulting changes under Data/ and Reports/. This is drift caused by this branch, not by a newly published REST version -- the spec set was pinned to Data/PfbCapabilityMap.json's generatedFrom list.
"@
    }

    Write-Host "All $($results.Count) checked artifact(s) are up to date."
} finally {
    if ($KeepWorkDirectory) {
        Write-Host "Scratch tree kept at $WorkDirectory"
    } elseif ($createdWorkDirectory) {
        Remove-Item -LiteralPath $WorkDirectory -Recurse -Force -ErrorAction SilentlyContinue
    } else {
        # A caller-supplied -WorkDirectory may hold things this script did not create, so only
        # the two subtrees it did create are removed.
        foreach ($dir in @($stagedSpecsDir, $outRoot)) {
            Remove-Item -LiteralPath $dir -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
}
